### ISSUE TITLE
Boostrap Server BootstrapFailureCause enum: v2 contains less codes comparing to v1

### ISSUE THREAD

**Issue by gerardolenski** [eclipse/leshan#1057]
Hi guys,

I'm upgrading Bootstrap Server with Leshan dependency from `1.3.1` to `2.0.0.-M4`. I realized that in the new library version the `BootstrapFailureCause` enum contains fewer error codes:
- in v1 there were also: `WRITE_ACL_FAILED`, `WRITE_SERVER_FAILED`, `WRITE_SECURITY_FAILED` and `DELETE_FAILED`
- in v2 there is just `REQUEST_FAILED` instead of above

Can you please explain why this change was done? Does `REQUEST_FAILED` mean that some of the WRITE or DELETE bootstrap operations just failed (without more details on which exactly object failure occurred)?

Many thanks,
Gerard

**Comment by sbernard31** [comment]
This change was done because we do a refactoring where BootstrapHandler is now more agnostic about request it sends. 
This allow to handle all kind of request (like the new discover or read request).
(More details about this could be found here : https://github.com/eclipse/leshan/pull/1027)

> Does REQUEST_FAILED mean that some of the WRITE or DELETE bootstrap operations just failed (without more details on which exactly object failure occurred)?

This means that the bootstrap session failed and so be stopped. The reason is that 1 request failed. Here you can not know which request failed. 

But there is now a [`BootstrapSessionListener`](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M4/leshan-server-core/src/main/java/org/eclipse/leshan/server/bootstrap/BootstrapSessionListener.java) which should be now more appropriate to watch bootstrap session lifecycle.

**Comment by gerardolenski** [comment]
Great. Thank you for the hint. I'll go with BootstrapSessionListener.
