### ISSUE TITLE
[CoapServer(main)#2] org.eclipse.californium.elements.UdpEndpointContextMatcher [83] -| request 39.144.14.51:50981 doesn't match 39.144.14.51:50982!        How to solve

### ISSUE THREAD

**Issue by limanyi185** [eclipse/leshan#1138]

**Comment by sbernard31** [comment]
Please could you do some efforts about clearly described your issue. :pray: 

Some advice about opening an issue. 

1. try to find a short description for your title issue.  (e.g. avoid to use logs in your title or at least keep only the relevant part)
2. Use the `comment` field to describe your issues. Give context, which version of Leshan you are using, describe how this happen. 
3. Try to put yourself in the place of peoples who will try to answer to your question.

About the `UdpEndpointContextMatcher [83] -| request 39.144.14.51:50981 doesn't match 39.144.14.51:50982` :
Do you get this at Client or Server side ? 
Which version of Leshan are you using ? 
Could you describe what you are doing when this happens ? 


Generally this happens when the foreign peer IP address/pot changes (e.g. when you are behind a NAT)

**Comment by sbernard31** [comment]
I will close this one but feel free to reopen if you have any  more input. 

Please if you open another issue try to improve your communication else I'm afraid we will not able to find a solution for you :grimacing:
