### ISSUE TITLE
Queue mode: most optimal way to retrieve data from device

### ISSUE THREAD

**Issue by sonny82** [eclipse/leshan#1151]
Hi,

We are working on an NB-IoT project where we would like to use leshan 2 server and bootstrap server, since we need support for LWM2M version 1.1 (currently we are using the latest milestone release leshan-2.0.0-M5).

In production somewhere around 10.000 - 15.000 devices are expected to be used (with DTLS-PSK security enabled).
Since the devices are battery powered queue mode is going to be used, where device would sleep most of the time but when it wakes up (most likely once per day) it should somehow send the latest data (values of around 10-15 resources) to our backend system (using the REST API). 
The client device (developed by external company) does not yet support queue mode so I cannot test this end2end yet.

I see 3 ways to implement this and I'm not sure which would make the most sense in terms of performance and scalability:

**Option 1: Composite observe request**
I would send a composite observe request on every registration (update)
When the device wakes up it should probably automatically send stored notifications (if notifIfDisabled property on server is set to true)
Question 1: is composite observe supported when using the queue mode? I think I read somewhere that it is not yet supported.  Unfortunately I cannot find the link at the moment :( 
Question 2: Would in this case the device send only the latest version of data or also all the history (we are only interested in the latest version of data).

**Option 2: Multiple single observe requests**
This would probably result in a lot of messages (1 or even more notifies for each observed resource) 

**Option3: Composite read**
We could register a presence listener which would notify our backend when device in online and at the same time also send relevant data (data would be retrieved using the composite read request.)
 
I hope my question is clear enough :)

Best regards,
Sonny

**Comment by sbernard31** [comment]
Some details to keep in mind, with queue mode when a device wake up, the specification says that it should start the communication with an UPDATE registration.

> The LwM2M Client lets the LwM2M Server know it is awake by sending a registration update message as a Confirmable message.

(source: http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#6-5-0-65-Queue-Mode-Operation)

If you respect the specification a wake up is at least 1 UPDATE  request and 1 piggyback UPDATE response. (2 messages)
(I know some user try to remove the update as technically this can sometime be done but this is clearly out of spec)

There is also the DTLS part, I'm not sure how often you will need to do DTLS handshake. But limiting the number of DTLS handshake is probably a good way to improve consumption.

------------------------------------------------
Know let's focus on your question.  (I consider that your data playload is small enough and will not use block wise transfer)

At first sight, I don't see any benefits of **Option2** comparing to **Option1**.

**Option1** I'm not sure if there is a consensus about this but I generally advice to avoid Coap-Observe when it exists  alternative. In your case I guess this can be easily avoided. 
Here you could have a look of my understanding of CoAP-Observe : https://github.com/eclipse/leshan/wiki/LWM2M-Observe
(I feel I should update this documentation, I will maybe do that if I found time and I will let you know about the update)
If you choose this way you will probably need to send the observe request on register. (2 messages)
Then each wake up a CON response (as I guess you don't want to loose data) + a ACK from the server (so 2 messages too).
(one of the annoying part, there is a state about the observe relation at client and server side which sometime is source of issues)

**Option3**
Comparing to **Option1**, this will consume maybe some more bytes as instead of a CON response + ACK, you will have a Read Request + piggyback response.

I would add a **Option4** about using a [Send Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-6-0-646-Send-Operation) 
I think this will also fit your use case. this will be 2 messages too (Send Request + piggyback response) 
In this case this is the client which decides the resources to send. 

So at first sight without any data lost at network level, I guess this will be pretty much the same for all solution. (2 messages)
Now if you really want to optimize this, I advice to first focus on DTLS part. 
Then if option 3 or 4 is OK to you go for it.
If you really want to optimize a lot (not sure this will pay-off), I guess you need to know exact payload size for each messages and also data lost and then try to estimate the cost of each option. (taking into account wake-up time because of retransmissions and also if large payload is often re-transmitted or not)

**Comment by sonny82** [comment]
@sbernard31 thank you for your explanation.
I just found out that the device appearantly doesn't support read-composite  and observe-composite  operations (I'm getting 501 status response). I also doubt the send operation is supported. Also if it would be it probably wouldn't return all the resources I need. So I will probably have to use object-level observe requests..

**Comment by sbernard31** [comment]
Note that when you are using Object-level observe requests, the whole object should be sent in each notification. (not only modified values or a subset of values)
That means that if you are able to go with Object-level observe requests, you probably can also go with Object-level read requests (in a same way you plan to use composite-read)
And again if you don't need specific feature of Observe request, I advice to keep the simple Read Request instead.

**Comment by sonny82** [comment]
Ok, thank you for help.
