### ISSUE TITLE
Adding X509-based security information does not work anymore

### ISSUE THREAD

**Issue by hannestschofenig** [eclipse/leshan#1163]
I have tried to use the Leshan Sandbox to add security information using X.509 credentials. Only two fields need to be entered, namely the endpoint name and the security mode. 

When I click "Add", then I get an error saying "Invalid Request Body". 

This was working just recently and I assume a recent code change broke this functionality

**Comment by sbernard31** [comment]
Thx for reporting this :pray:

I was out of office yesterday. I will look at this.

**Comment by sbernard31** [comment]
I guess this is a regression introduced with https://github.com/eclipse/leshan/pull/1122
(So this bug should not affects any release, only `master` branch and so the sandbox)

The issue comes from line : 
https://github.com/eclipse/leshan/blob/3d2b1f990e99fd2419972de435f87a470bd839ec/leshan-server-demo/src/main/java/org/eclipse/leshan/server/demo/servlet/json/JacksonSecurityDeserializer.java#L104

I guess this should rather be : `! x509.isMissingNode()` 
but I will even go with something like `x509 != null` like the rest of the code in this file. :thinking: 
@Michal-Wadowski is there any reason I missed, that explain the usage of `isMissingNode()` ?

**Comment by Michal-Wadowski** [comment]
@sbernard31 I don't remember why i used isMissingNode() here :thinking:. But your fix with ```x509 != null``` seems to be ok for me.

**Comment by sbernard31** [comment]
This should be fixed in `master` and on sandbox now.

**Comment by hannestschofenig** [comment]
Thanks for the quick reaction time.

**Comment by sbernard31** [comment]
Thx for reporting issue that really help :pray:
