### ISSUE TITLE
Script to create bootstrap.json config files?

### ISSUE THREAD

**Issue by hannestschofenig** [eclipse/leshan#1172]
I have been wondering whether someone of you has written a script (shell, Python, whatever) to create the content of the bootstrap.json file based on input data (e.g. certificates, private keys, etc). 

Using the Web UI is great but it obviously has limitations. Using a text editor is fun but not when using long certificates.

**Comment by sbernard31** [comment]
I guess you talk about `leshan-bsserver-demo` ? 

Just to be sure, you're fine with the current UI but you would like a way to add a new bootstrap configuration via an API ? 
OR if the UI was better you don't need this API (like being able to select a file instead of copy/paste Hexa) ?  

Currently, the REST API is intended to be used by the UI but I know there is a lot of user which use it directly. 

> I have been wondering whether someone of you has written a script (shell, Python, whatever) to create the content of the bootstrap.json file based on input data (e.g. certificates, private keys, etc).

[Here](https://github.com/eclipse/leshan/issues/374) there is a python script which allows to create the config using REST API. (I didn't test it recently so maybe it is a bit obsolete and should be adapted).
I guess the missing part for you is getting a filepath as input then convert the file content in an array of byte (E.g. : `[115,101,99,114,101,116,95,107,101,121]`)

**Comment by sbernard31** [comment]
@hannestschofenig  do you succeed to do what you wanted ? 
Do not hesitate to share code here :pray:

**Comment by sbernard31** [comment]
Should I close this one ? If you need help do not hesitate to ask ?

**Comment by sbernard31** [comment]
I close this one. But feel free to reopen if needed.
If you have a script or any feedback about this, do not hesitate to share.
