### ISSUE TITLE
Is Leshan affected by log4j2 CVE-2021-44228 vulnerability ?

### ISSUE THREAD

**Issue by kiran-g** [eclipse/leshan#1178]
I am using leshan version 0.1.11 which is having log4j v2.1 as dependency. As you all are aware this version of log4j  is having a severe [vulnerability](https://www.whitesourcesoftware.com/resources/blog/log4j-vulnerability-cve-2021-44228/). 

Modifying the HTTP request body seems to be the usual way to exploit this. In my case the Lehan HTTP API is not exposed outside. Only the UDP interface is public. UDP encryption is also enabled. 

How vulnerable is my leshan installation? Is UDP interface also at risk? 

I confirm that I will not hold you responsible for any  negative impact of your answer.

Note: If this is an inappropriate or invalid question, kindly delete

**Comment by boaks** [comment]
You write, you use a 5 years old (pre-) release?

I'm not sure, why you worry about vulnerabilities, if you missed 5 years to update leshan.

Leshan 0.1.11-M14 uses Californium 2.0.0-M2, so I can only very strongly recommend, that you migrate at least to the latest bugfix-release of Leshan in order to use also the latest bugfix-release of Californium.

See [Security Policy](https://github.com/eclipse/leshan/security/policy).

**Comment by sbernard31** [comment]
> I am using leshan version 0.1.11 which is having log4j v2.1 as dependency. As you all are aware this version of log4j is having a severe vulnerability.

There is no 0.1.11 version, only milestones one (from 0.1.11M1 to 0.1.11M14).
0.1.11M1 was released in begin of 2015 the 0.1.11M14 end of 2016.

So you are using a development version which are very very old and you worried about security issue about log4j2.
That sounds strange to me. :thinking: 

Please if you are deploying Leshan in a context which needs a good level of security,  use the last stable version... currently [leshan-1.3.1](https://github.com/eclipse/leshan/releases/tag/leshan-1.3.1) (and update to the last one regularly).  
You should also use the last 2.6.x version of californium. Currently there is no recent version of Leshan with last 2.6.x version but as no API break is expected, you should be able to use the last 2.6.x. About this last point, I currently don't know if I should do Leshan release just to bump this kind of version (without any leshan code changes) ...

> In my case the Lehan HTTP API is not exposed outside.

If you are talking about HTTP API, I guess you also use Leshan demo which is not intended to be used in production ...

> How vulnerable is my leshan installation? 

About the log4j2 issue I don't know if your installation is exposed. This is not really a Leshan question because : 
The only part which is intended to be reused is the Leshan library (not the demo)
The Leshan library just depends of [slf4j facade](http://www.slf4j.org/).
This is up to the user to chose the slf4j back-end and version. 
So you should be able to update to a more recent version of log4j2 or to switch to a recent logback.

> Is UDP interface also at risk?

As I said about log4j2 issue I don't know but for reasons exposed above : 
- using an unmaintained, old, not stable, development version ...
- reusing demo code (not production ready) in production.

I guess we can consider that your installation is risky.

> Note: If this is an inappropriate or invalid question, kindly delete

Do not delete it, maybe this will help other users.

**Comment by kiran-g** [comment]
Thanks everyone for the  replies. Please note that my application is  reaching end-of-life and there is no plan/motivation to do an upgrade. My idea is to keep the application secure for the remaining few months. 

I could see the following warning when I build leshan:
```
        [WARNING] Unused declared dependencies found:
        [WARNING]    org.apache.logging.log4j:log4j-core:jar:2.1:runtime
        [WARNING]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.1:runtime
```

Does it mean that log4j is not used ? Or is it just how slf4j-facade works?

**Comment by sbernard31** [comment]
> My idea is to keep the application secure for the remaining few months.

My point is that there is probably several other known vulnerabilities (not linked to log4j2)  in your version. 

> Does it mean that log4j is not used ? Or is it just how slf4j-facade works?

I'm not able to answer without more context.
**But again Leshan library is not dependent to log4j2.** 
So you are the only one who is able to know if you are using log4j2 as backend or something else...
If you are using it and you are worried about that point, just upgrade the version or change to another slf4j backend.

**Comment by boaks** [comment]
What I did for some Californium demos was to check the "with-all-dependencies.jar" if they contain  `org.apache.logging.log4j`. I'm not sure, but if I remember well, there is also such a jar for the leshan demo server. so check the jar you're using, if that contains `org.apache.logging.log4j` at all.

**Comment by boaks** [comment]
I built a `leshan-server-demo-0.1.11-M14-jar-with-dependencies.jar` and unfortunately, it contains `org.apache.logging.log4j`. Which version and If these classes are really used, I don't know.

**Comment by kiran-g** [comment]
Thanks Achim. I could verify from mvn dependency tree that the  version of log4j is 2.1. The [fix](https://msrc-blog.microsoft.com/2021/12/11/microsofts-response-to-cve-2021-44228-apache-log4j2/) I am going to use is to  open the jar file and remove "JndiLookup.class".

**Comment by sbernard31** [comment]
_Just a sumarize for others :_

**Is Leshan affected by log4j2 [CVE-2021-44228](https://www.whitesourcesoftware.com/resources/blog/log4j-vulnerability-cve-2021-44228/) vulnerability ?**

Leshan **Library:** 
 -  **:heavy_check_mark: Not affected**, this is only part which is intended to be used in production and it just depends on [**slf4j**](http://www.slf4j.org/) facade.   So up to users to check which slf4j backend they are using.  

Leshan **Demos:**  (note that [demos should not be used in production](https://github.com/eclipse/leshan/wiki/F.A.Q.#could-i-reuse-leshan--demo-)). 
 - **:heavy_check_mark: Not affected since 1.0.0-M5** (January 2018),  since this milestones, logback is used as backend for demo.
 - **:warning: Affected until 1.0.0-M4** (September 2017),  log4j v2.1 or lower are used by **server** and **bsserver demo**.
 
General security recommendation : 
 - Do not use old milestones or unstable version, rather use last stable (1.x) version or 2.0.0 milestones.  (See [Security](https://github.com/eclipse/leshan/security/policy))
 - Do not use demos in production. 
 
 You could also be interested by californium information about that : https://github.com/eclipse/californium/issues/1848

**Comment by sbernard31** [comment]
I think we can close this one.
(There is a eclipse page for all eclipse project about this :https://wiki.eclipse.org/Eclipse_and_log4j2_vulnerability_(CVE-2021-44228))
