### ISSUE TITLE
LWM2M version validation 

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#1207]
Hi,

Leshan version : leshan-2.0.0-M3

There is a validation on lwm2m version for registration request received . This code does not allow if lwm2m version sent is 1.0.2 .

org.eclipse.leshan.core.LwM2m.Version.validate method.

```
if (versionPart.length != 2) {
                return String.format("version (%s) MUST be composed of 2 parts", version);
            }
```

Is it possible to remove this validation or allow it work for version 1.0.1 or 1.0.2 . 

Thank you.

**Comment by sbernard31** [comment]
As I understand the specification, the LWM2M version in registration must be the LWM2M enabler version.
The specification defines it at : `1*DIGIT "." 1*DIGIT`
The [`PATCH` version](https://semver.org/) must not be present,  so in your case the version should be `1.0` and not `1.0.2`
The server does not need the PATCH version as all 1.0.x version should behave in a same way. (the PATCH number is just about fixing some bug in the specification, not changing behavior).

If this is possible to you, I strongly advice you to fix your device instead of hack at server side.

Anyway, about a workaround at server side you should look at : https://github.com/eclipse/leshan/issues/1103#issuecomment-937784837  
It seems the `MessageInterceptor` way is better. 
You will not be able to remove the validation (I'm not sure there is an easy way to do that) but you will be able to change/fix the request sent by the client. (replace 1.0.2 by 1.0 before this is handled by Leshan)

**Comment by madhushreegc** [comment]
Ok . Thankyou so much for your reply. 

I will ask the device vendor to fix this issue else I will look in to the workaround .
