### ISSUE TITLE
We use the Leshan framework to test the lwm2m FOTA use case of VZW and find a problem of restoring the observe subscription message. 

### ISSUE THREAD

**Issue by JameslaoA** [eclipse/leshan#1216]
The details are described below：
Verizon fota flow:
![image](https://user-images.githubusercontent.com/17543107/156366425-d48a7480-8331-4998-ae7c-0231560c5a07.png)

Before the upgrade the server has subscribed to the 5 / 0 / 3 message, but device reboot after firmware update, the 5 / 0 / 3  status cannot be reported to the server.

Problem scenario:

Before upgrading the device, the status of downloading the FOTA package is 2. There are subscription messages on 5 / 0 / 3. You need to save the mid, token, token length and other information. After upgrading the device FOTA, register the server and send the mid token and token length information to the subscriber through notify

Requirements:
1. Can Leshan framework save subscription messages? What is the interface for saving subscription messages?

2. How to send the status to the server subscribing to the message after the device is restarted?

pls help us to confirm the issue.

Thanks.

**Comment by JameslaoA** [comment]
Yes，we use demo-client as a lwm2m client and register with the Verizon lwm2m Server.

**Comment by boaks** [comment]
AFAIK, leshan/californium has only implemented to persist:

Leshan:
- lwm2m server - coap-notification-client

Californium:
- dtls state

With that, it's not possible to restart the java leshan demo-client with an active coap-notification-server.
Anyway, you may just try to emulate such a restart, in order to be closer to the real device.

The real device's implementation must then be one, which support such restart of a coap-notification-server, but I guess, that's even not java, or?

**Comment by JameslaoA** [comment]
Do you know where to save token / token length / message ID  in code？Do you know which java file it is?

How to build a new COAP message and send it to the server in code?

**Comment by boaks** [comment]
Just don't stop your java demo-client, that's the simplest way.
Everything else, isn't that easy.

**Comment by sbernard31** [comment]
Just to be sure when you say  _"server has subscribed to the 5 / 0 / 3 message"_,  you mean "server establishes an observation relation on /5/0/3 resource" (by sending an observe request) ? 

Looking at the picture you shared, I don't see any observe request  before the reboot, but I guess this is just a flow chart issue ?

Let's assume server sends this observe request before the reboot, I also see that client do a registration just after the reboot.
As I understand the specification, a new registration means that previous observe relation are forgotten.
From [LWM2Mv1.1@core§6.4.1. Observe Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-1-0-641-Observe-Operation)
> Until the LwM2M Client sends a new registration, the LwM2M Server expects the LwM2M Client to remember the observation requests. If a LwM2M Client forgets the observation requests (e.g. device factory reset) it MUST perform a new "Register" operation. The LwM2M Server MUST re-initiate observation requests whenever the LwM2M Client registers.

So unless I missed something, the **LWM2M FOTA use case of VZW does not make sense** to me, because client should not send a notification after the registration and server should re-established the observe relation if needed by sending a new observe request ... 

(Maybe out of topic but I would not build the critical firmware update feature on observe feature or I hope this server are using some polling/timeout mechanism in addition...)

> Can Leshan framework save subscription messages? What is the interface for saving subscription messages?

Leshan client (demo or library) is not able to do that.
Looking at @boaks  answer, I understand there is no API to do that with Californium (the coap stack used by leshan)
Even if this was possible I feel this would not make sense to persist observe relation after a REGISTER.
(There is maybe some use case where this could make sense but not this one)

Anyway as @boaks propose the simple way is maybe to just emulate the reboot. 

> Do you know where to save token / token length / message ID in code？Do you know which java file it is?
> How to build a new COAP message and send it to the server in code?

If you want to test this use case anyway,  I guess you can try this kind of ugly workaround : 
- https://github.com/eclipse/leshan/blob/21bf6b9eda1ecb1c8e0c87b28bd89c494ef8d1a2/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/observe/ObserveTimeStampTest.java#L122-L123
- https://github.com/eclipse/leshan/blob/21bf6b9eda1ecb1c8e0c87b28bd89c494ef8d1a2/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/util/IntegrationTestHelper.java#L380-L383
- https://github.com/eclipse/leshan/blob/21bf6b9eda1ecb1c8e0c87b28bd89c494ef8d1a2/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/observe/TestObserveUtil.java#L31-L51

**Comment by JameslaoA** [comment]
@sbernard31 

Until the LwM2M Client sends a new registration, the LwM2M Server expects the LwM2M Client to remember the observation requests. If a LwM2M Client forgets the observation requests (e.g. device factory reset) it MUST perform a new "Register" operation. The LwM2M Server MUST re-initiate observation requests whenever the LwM2M Client registers.
---
I understand what you said, but after communicating with Verizon and confirming that they need to receive the subscription message before upgrading, save the token token length mid corresponding to the subscription message, and form a SOAP message through the saved token information after upgrading to send it to the server, so that the server can receive the 5 / 0 / 3 status reported by us and the test can pass.

pls refer to the pcap log:
![image](https://user-images.githubusercontent.com/17543107/156390833-034fba01-ac01-4d5a-ac23-f3b9e9df6e86.png)

I don't know which part of the code token/token length/Mid is used, so I ask you help me.
Secondly, after the upgrade, how can I re build a new COAP message from the token and other information saved before the upgrade and send it to the server so that the server can observe the 5 / 0 / 3 we reported.(We want to achieve this function)

pls help to check and reply us,thanks.

**Comment by sbernard31** [comment]
>  I understand what you said, but after communicating with Verizon and confirming that they need to receive the subscription message before upgrading

Verizon ask to devices to not follow the LWM2M specification ... It's hard to me to understand that ... :expressionless: 
(or I maybe missed something and so this will be more relevant to discuss about this)

> , save the token token length mid corresponding to the subscription message, and form a SOAP message through the saved token information after upgrading to send it to the server, so that the server can receive the 5 / 0 / 3 status reported by us and the test can pass.

It's not so easy to understand you. :tired_face: 
I guess "subscription" means "notification" ....
SOAP means CoAP ...
I don't think you need to save MID, TOKEN is enough. See https://datatracker.ietf.org/doc/html/rfc7641

I get all of those you already explained it. 

> I don't know which part of the code token/token length/Mid is used, so I ask you help me.

You should be able to retrieve it using a `MessageInterceptor` on `Endpoint` but this is more crappy hack :confused: 

> Secondly, after the upgrade, how can I re build a new COAP message from the token and other information saved before the upgrade and send it to the server so that the server can observe the 5 / 0 / 3 we reported.

Already explained above :point_up:.
I will not go more in details than this.

But again all of this sounds not so easy, so **why not just start by trying the simple way proposed by @boaks**  _"Just don't stop your java demo-client, that's the simplest way."_ ...

**Comment by sbernard31** [comment]
:broken_heart:  screenshot & wireshark capture : a long love story :broken_heart:

**Comment by sbernard31** [comment]
should we close this issue ?

**Comment by sbernard31** [comment]
I close this issue but feel free to reopen if needed.
