### ISSUE TITLE
Overlapping paths in Observe-Composite

### ISSUE THREAD

**Issue by adamsero** [eclipse/leshan#1253]
Right now, while creating a new Composite Object, Leshan Server Demo warns the user that _"Overlapped path will not work. (e.g. /3/0 with /3/0/1 is not valid)"_. Indeed, after adding two or more overlapped paths and trying to execute a Composite operation, an error will occur.

While it doesn't make sense for Read-Composite to allow overlapped paths, it might be different for Observe-Composite. According to LwM2M specification, this operation allows to set Attributes at each level of a path, e.g.:

"/3442/0" with Attribute pmin=60
"/3442/0/110" with Attribute pmin=30

It means that for all resources of Object 3442/Instance 0, any change to them will be reported after at least 60 seconds from the last notify **except** the resource 110, for which it will be 30 seconds.

In **LwM2M 1.1** the Attributes are set globally before starting an Observe operation, which makes overlapping paths obsolete.

In **LwM2M 1.2** however, the Attributes can also be set doing the Observe, overriding the global settings. In this case, the Leshan Server implementation is mostly OK, but the Client side is lacking some features - it must take into account the Attributes defining the wait period between notifications. It also must not send the same data twice for overlapping resources.

So, we can either:
a) Make the Client side compatible with LwM2M 1.2 for the future. It will also be potentially better in terms of interoperability as the Clients would be able to communicate with non-Leshan based platforms in terms of path overlapping.
b) Make the Client reject an Observe request with overlapping paths. Right now, Client accepts the request and the error occurs on the server side while decoding the payload.

Let me know which option you prefer.

**Comment by sbernard31** [comment]
**historic**
When I implemented this feature. I asked myself if we should support this :thinking:  ?
I decided to not support overlapping because I didn't see any benefits of this.
But you probably right this makes sense for LWM2M v1.2 for reason you express. 

**additional info**
Not directly linked to your question but could worth to know: 
- current client Leshan implementation does not support Write Attribute (and so observe does not use pmin, pmax ...)
- there is some missing clarification about how works attribute attachement. (https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/478#issuecomment-1031352743)

**current state**
Tell me if I'm wrong but the current state is : 
- leshan-server-demo ui doesn't allow overlapped path
- `ReadCompositeRequest` does not allow it (there is a check in the code)
- I didn't see the same check in `ObserveCompositeRequest`
- the decoder at server side does not support overlapped path ? (I look at this quickly I didn't see where is the issue)

 At client side, it is not clear to me if this works or not ? 
 Your b) seems to says yes but your a) make me think there is something to implement at client side ?
 
**what do we want ?**
 Currently we are targeting LWM2M v1.1.
 Personally, I'm not sure we want to make our client compatible with LWM2M v1.2.
 But even if we put LWM2M v1.2 aside,  I think we can ask ourself if we should support/tolerate overlapped path ?
 
 You are saying that : 
 > It will also be potentially better in terms of interoperability as the Clients would be able to communicate with non-Leshan based platforms in terms of path overlapping.
 
 Do you know such kind of platform ?
 If you think we should support it. I'm not against the idea.
 If we decide to support it I'm not sure about this impact ?
 If we decide to not support it, I guess this is mainly about adding in `ObserveCompositeRequest` the same kind of check there is in `ReadCompositeRequest` ?

**Comment by adamsero** [comment]
> - leshan-server-demo ui doesn't allow overlapped path

I'm pretty sure it allows users to create a Composite Object with overlapping paths as seen here:
![image](https://user-images.githubusercontent.com/37634022/168099237-bbfb7c34-abee-4922-b0b6-0e165575af81.png)

> - ReadCompositeRequest does not allow it (there is a check in the code)
> - I didn't see the same check in ObserveCompositeRequest

That is true

> the decoder at server side does not support overlapped path?

Yes, the exception states:
`CodecException: 2 RESOURCE nodes (LwM2mSingleResource [id=110, value=initial value, type=STRING],LwM2mSingleResource [id=110, value=initial value, type=STRING]) with the same identifier 110 for path /3442/0/110`
It's being thrown in `LwM2mNodeSenMLDecoder` line 462

> At client side, it is not clear to me if this works or not ?
Your b) seems to says yes but your a) make me think there is something to implement at client side ?

Right now there is no error occurring on the client side, but the response for overlapping paths is still wrong. We should either (a) accept path overlapping which would require modifying the client implementation to suit LwM2M 1.2. or (b) reject the path overlapping completely upon detecting it on the client side. Right now it's a mix of both - the client accepts the request but returns duplicated resources which in turn cause decoder exceptions on the server side.

I'm not yet sure what we want exactly, I need to discuss it further with my team and I will let you know afterwards.

**Comment by adamsero** [comment]
Ok, after some discussion we decided to go for option C, which is:
- Enable sending overlapped paths in Observe-Composite request on the server side and accept it on the client side.
- Remove overlapped data from client's response
- Ignore attributes for the time being

This is a compromise between options A and B - we don't take attributes into account for now as it seems like a pretty complex topic. The important part is to remove overlapped data (nodes) from the response's payload so as not to cause any errors on the server side while decoding. I wrote some methods for that purpose and committed on [opl/overlapping_paths_support_for_client](https://github.com/przem83/leshan/tree/opl/overlapping_paths_support_for_client).

In more detail, the main method for removing overlapped nodes works as follows:
Suppose the server requests an observe on /1/0/2 and /1/0. The algorithm will detect that /1/0 contains /1/0/2 among other resources and it will be removed from response data. The result will simply be /1/0.
I wrote a few tests, so you can take a look at them for more examples.

Let me know if you think option C is viable 🙂.

**Comment by sbernard31** [comment]
Before to define how we support this.
I would like to better understand the reason about why we want to support it (overlapped path) ? (sorry if you already explained it)

Is it driven by some needs you have ? or is it to try to fix something you consider as not consistent ? or ? 
Knowing exactly why we do that will help to to know how to do it.

**Comment by adamsero** [comment]
One reason for it is that the current implementation causes errors: Leshan server is able to send a request with overlapped paths but is unable to decode overlapped nodes. According to LwM2M specification, a LwM2M server should allow performing Observe with overlapped paths without any errors, hence my efforts to fix what's currently implemented.

**We don't need to** have Leshan client remove the overlapped nodes before sending them to the server - we can make the server accept the overlapped nodes from the client's data. I just went for the first option, but if you prefer we can switch the approach and fix it from the server side.

**Comment by sbernard31** [comment]
> Leshan server is able to send a request with overlapped paths but is unable to decode overlapped nodes.

OK so the main goal is to remove this inconsistency. 

>  According to LwM2M specification, a LwM2M server should allow performing Observe with overlapped paths without any errors, hence my efforts to fix what's currently implemented.

For LWM2M 1.1, this is not so clear. Not clearly allowed, Not clearly forbidden. Like for ReadComposite or I missed something ?

For read we agree this doesn't make so mush sense.  
For observe, this could make sense for LWM2M 1.2 but for LWM2M 1.1 this makes no sense too.  
Right ?

So how could we fix the inconsistency ?
For LWM2M 1.1 (leshan-2.0.0), I feel, the fast and easy way, we just don't allow to send overlapped path for observe request too.  (like in ReadCompositeRequest constructor)

If we consider we must tolerate overlapped path, there is several point : 
- if we tolerate it for observe, I feel we should tolerate it for read too ? because in LWM2M 1.1 there no more reason to support one than the other ?
- we should tolerate that a client send overlapped data. (because nothing in the specification define how overlapped path should be handled ?)
- Leshan client should ideally remove overlapped data. (for optimization reason but maybe this could be consider as optional)

But again I'm not sure this really pay-off to support this ?

**Comment by sbernard31** [comment]
> We NEED to forbid Leshan Server from sending Observe-Composite request just as Read-Composite request (that will be compliant with LWM2M 1.1 as you said).

OK let's go for this one.

> We MAY also have Leshan Client remove overlapped data just in case

I think if we implement the first point :point_up:,  this will make client to send Bad Request response when it receive Observe-Composite request with overlapped path. 

In my opinion, it's OK like this. Eventually if we face a user who needs support of overlapped path for concrete reason, we could rethink about all of this. :slightly_smiling_face:

**Comment by adamsero** [comment]
As expected, this was fairly easy to do, I implemented both points on [opl/forbid_overlapped_paths](https://github.com/Przem83/leshan/tree/opl/forbid_overlapped_paths). Should be ready for PR, unless you want to do something else with it.

**Comment by adamsero** [comment]
It's on #1263
