### ISSUE TITLE
API interface access frequently times out

### ISSUE THREAD

**Issue by 18715001062** [eclipse/leshan#1278]
When I read and write object resources through the northbound API interface, request timeouts frequently occur. 
Is this problem caused by frequent requests to the server, or is it caused by too small network bandwidth?
Is there a lot of settings registered on leshan at the same time, the server request cannot be processed, is there any solution?

**Comment by sbernard31** [comment]
> Is this problem caused by frequent requests to the server, or is it caused by too small network bandwidth?

It could be cause by so many different thing and it's pretty impossible to answer to this kind of question without more context.

But looking at your previous problem (https://github.com/eclipse/leshan/issues/1199), we bet that you are in "client IP changing" environment  (probably because of NAT or something like this).

So if you send Request several minutes after last device communication, then probably its IP changes or NAT route is closed and so you request will timeout...

If you're in "client IP changing" environment, you need to use Queue Mode which is a kind of client initiated mode.

>  Is there a lot of settings registered on leshan at the same time, the server request cannot be processed, is there any solution?

I don't get the question what is _"a lot of settings registered on leshan"_ ?

**Comment by sbernard31** [comment]
I close it as I didn't get any answer to my question but feel free to reopen if needed.
