### ISSUE TITLE
Question to Certificate Chains

### ISSUE THREAD

**Issue by Earthworn** [eclipse/leshan#1392]
### Question

Hi, 

I m aware, that you can only put one certificate in the public_key_or_identity field on client side because of the specification. What if a Client doesn't follow the specification and it is possible and the chain is send successfull. Can the Leshan Server work with the chain and trace it back to the Root Certificate. And is it possible to write during bootstrap with a Leshan Bootstrapserver a Certificate Chain to the public_key_or_idenity field? 

Best regards Levi

**Comment by sbernard31** [comment]
> I m aware, that you can only put one certificate in the public_key_or_identity field on client side because of the specification

I understand the specification in the same way.
You can read https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/502 to better understand issues linked to this "limitation".

LWM2M authors fix this limitation in LWM2M v1.2.1, see [LWM2M-v1.2.1@transport§5.2.9.3. X.509 Certificate Mode](http://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_2_1-20221209-A.html#5-2-9-3-0-5293-X509-Certificate-Mode): 
> _"The "Public Key or Identity" Resource MUST be used to store the X.509 certificate of the TLS/DTLS client (i.e. end-entity certificate) and, if available, some or all of the certificates chain up to the root CA certificate. DER encoding [RFC5280] MUST be supported by the LwM2M Client and the LwM2M Bootstrap-Server. PEM encoding [RFC7468] MAY be supported by the LwM2M Client and LwM2M Bootstrap-Server. While the PEM encoding is more verbose than a DER encoding it allows multiple certificates to be transmitted._"

But for now there is no Leshan version which implements LWM2M v1.2.x.
(Leshan v1.x targets LWM2M v1.0.x and Leshan v2.x targets LWM2M v1.1.x)

> What if a Client doesn't follow the specification and it is possible and the chain is send successfull. Can the Leshan Server work with the chain and trace it back to the Root Certificate.

Currently, I guess this should work. :thinking: 

> And is it possible to write during bootstrap with a Leshan Bootstrapserver a Certificate Chain to the public_key_or_idenity field?

This should maybe work ... :thinking: 
But there is at least one issue with `InMemoryBootstrapConfigStore` which use  `ConfigurationChecker` to check the bootstrap config. 
`org.eclipse.leshan.server.bootstrap.ConfigurationChecker.checkX509(ServerSecurity)` will probably failed because it will try to check that `serverPublicKey` is **one** valid X509 certificate.
But it should be possible to override this behavior OR to implement your own `BootstrapConfigStore`. 


:warning: If you go in that way with LWM2M v1.0.x or v1.1.x, you will be out of specification, and so   : 
 - this could bring to interoperability issue 
 - If my guess is right and Leshan v1.x or v2.x supports this behavior,  this is not really desired, so no guarantee this will be always true. 

If one day there is a Leshan v3 targeting LWM2M v1.2.x, then this version will fully support this use case. 

HTH

**Comment by Earthworn** [comment]
Thank you. That was helpfull
