### ISSUE TITLE
Resources 13 to 20 aren't implemented in leshan server

### ISSUE THREAD

**Issue by Warmek** [eclipse/leshan#1393]
### Question

Some lwm2m resources from Server object are missing on Leshan Bootstrap module.
For lwm2m Server object on Leshan side all resources are implemented excepted resources from 13 to 20. Resources from 21 onwards seems to be present.

**Comment by sbernard31** [comment]
Yep, this is not implemented because there is an issue with model from registry.

All those resources are declared as EXECUTABLE resource.
This is a bug in the model, See : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/519

If you read issue :point_up: and as OMA doesn't want to fix their model, you will see there is no clear consensus about what should be the best move for Leshan :disappointed:

Your issue description looks like just a "fact" enumeration but is there some needs behind this ? could you elaborate a bit more ?

**Comment by Warmek** [comment]
The question would be if we can implement those resources and if so how to do it? But from what i understand it seems that this will not be possible

**Comment by sbernard31** [comment]
Not impossible but at least we need to think about pros and cons before to implement it. 

If you strongly need it, it may worth to find a solution.  
else maybe better to let it like this for now and then implement it for Leshan 3.x which will target LWM2M v1.2.

**Comment by sbernard31** [comment]
@Warmek so do you need this feature OR this was just for sake of completeness ?

**Comment by Warmek** [comment]
I would like have this feature implemented especially as right now operations those fields aren't defined and becouse of this we can change them to for example read and it wouldn't affect compability. Also it would give those fields some usage as right now we can't do anything with them

**Comment by sbernard31** [comment]
I still don't get if you really need it in a specific production use case OR just because you think it will be better for Leshan. :sweat_smile: 

Anyway, I get your point and maybe we will change this before.
But before to jump on this, I try get feedback from OMA : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/519#issuecomment-1434869338

**Comment by sbernard31** [comment]
Just for the update : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/519#issuecomment-1435447461

@Warmek, if wanted you can start to work on this.
I guess first thing to do is to fixed the model  [`1-1_1.xml`](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M10/leshan-core/src/main/resources/models/1-1_1.xml)
You should probably looking at [`1-1_2.xml`](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/version_history/1-1_2.xml) for buggy resources.

I think we should also probably rename that file into something like  `1-1_1-fixed.xml`

**Comment by sbernard31** [comment]
Some news from OMA : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/519#issuecomment-1468344412
Following this :point_up:, no need to use a different model. (I don't know if this will be an issue with Leshan code, we will see)

**Comment by Warmek** [comment]
I've created [xml-fixed](https://github.com/Warmek/leshan/tree/xml-fixed) with `1-1_1-fixed.xml` file. I've implemented same operations as OMA did in their fix

**Comment by sbernard31** [comment]
In my last commit just above (https://github.com/eclipse/leshan/issues/1393#issuecomment-1470057320), I said that finally _"no need to use a different model"_ 
So unless you find some issue about keeping previous model, we should first try to follow OMA advices.

**Comment by Warmek** [comment]
OMA said that those resources are supposed to be set in Bootstrap. I've added them to ServerConfig in BootstrapConfig.java.
 I've made a commit on [opl/AddBootstrapAttributes](https://github.com/JaroslawLegierski/leshan/tree/opl/AddBootstrapAttributes).

**Comment by sbernard31** [comment]
I think this is the right way.
Did you test it ? 
You can create a PR about this.

**Comment by sbernard31** [comment]
This is now integrated in `master` thx to PR #1435.
I guess we can close this issue. 

Thx @Warmek to moved this forward.
