### ISSUE TITLE
How will Refuse to register

### ISSUE THREAD

**Issue by xwh1108** [eclipse/leshan#1419]
### Question

I want the device to be registered in accordance with my rules, for example, the server should refuse to register the device if it does not contain a value

**Comment by sbernard31** [comment]
You implements your own LWM2M server based on Leshan library and you want to authorize client to register using your own rules, correct ? 

You should be able to do that implementing your own `Authorizer`.
See default implementation : `DefaultAuthorizer` because you probably need to extend it.
And `LeshanServerBuilder.setAuthorizer(Authorizer)` to use your custom `Authorizer`.

See : 
```java
/**
     * <p>
     * Set your {@link Authorizer} implementation to define if a device if authorize to register to this server.
     * </p>
     * By default the {@link DefaultAuthorizer} implementation is used, it needs a security store to accept secured
     * connection.
     */
    public LeshanServerBuilder setAuthorizer(Authorizer authorizer) {
        this.authorizer = authorizer;
        return this;
    }
```

By exploring `LeshanServerBuilder` class, I guess this was not so hard to find :wink:

**Comment by sbernard31** [comment]
(let me know if this solves your problem and If we can close this issue)

**Comment by xwh1108** [comment]
> (let me know if this solves your problem and If we can close this issue)

yes,It solved my problem 😊
