### ISSUE TITLE
Resources with no defined operations MUST NOT be considered as executable

### ISSUE THREAD

**Issue by Warmek** [eclipse/leshan#1441]
### Question

Should resources with no defined operations be defined as executable in leshan server demo? For example, resource 13 in 1-1_1.xml don't have any operation defined but in leshan server demo it's displayed as executable.

**Comment by sbernard31** [comment]
> Should resources with no defined operations be defined as executable in leshan server demo?

Nope, this is a bug.

**Comment by Warmek** [comment]
I want to fix it. Where should I start looking for assigning label for this button?

**Comment by sbernard31** [comment]
Just to be sure we are talking about `master` ? (not `1.x` branch ?)

**Comment by sbernard31** [comment]
If this is about `master`.
I take a look at what is sent by the REST API by using my browser developer Tools. 
And I see for resource 13 : 
```json
{
	"13": {
		"id": 13,
		"name": "Registration Priority Order",
		"operations": "NONE",
		"instancetype": "single",
		"mandatory": false,
		"type": "unsigned_integer",
		"range": "",
		"units": "",
		"description": "The LwM2M Client sequences the LwM2M Server registrations in increasing order of this value. If this value is not defined, registration attempts to this server are not impacted by other server registrations."
	}
}
```

And looking at : 
https://github.com/eclipse/leshan/blob/d5052f181918af3680eb42a7428810a8fb65bcdd/leshan-server-demo/webapp/src/components/resources/ResourceControl.vue#L40-L45

and : 
https://github.com/eclipse/leshan/blob/d5052f181918af3680eb42a7428810a8fb65bcdd/leshan-server-demo/webapp/src/components/resources/ResourceControl.vue#L95-L97

It seems that returning `NONE` or checking String contains `E` is not a good idea ?
I don't know what is the best move... 
Maybe returning empty String instead of `NONE` ?
Or check that operation is strictly equals to E ? using includes make sense for `R` or `W` but not for `E`
See : https://github.com/eclipse/leshan/blob/d5052f181918af3680eb42a7428810a8fb65bcdd/leshan-core/src/main/java/org/eclipse/leshan/core/model/ResourceModel.java#L26-L40

**Comment by Warmek** [comment]
I've created a fix on [opl/EXEButton](https://github.com/JaroslawLegierski/leshan/tree/opl/EXEButton).
I went with strictly comparing operation to "E" as I feel like switching from NONE to empty string could be confusing when debugging some issues.
To future-proof from similar issues we could change Operation "NONE" to "none" so it would be possible to have any possible combination of operations, but it seems redundant

**Comment by sbernard31** [comment]
> I went with strictly comparing operation to "E" as I feel like switching from NONE to empty string could be confusing when debugging some issues.

I also feel this is the best way.  :slightly_smiling_face: 

You can create a PR.

**Comment by Warmek** [comment]
I've created a [PR](https://github.com/eclipse/leshan/pull/1442)

**Comment by sbernard31** [comment]
Fixed in `master`. (see #1442)

**Comment by sbernard31** [comment]
Thx @Warmek :pray:
