### ISSUE TITLE
Leshan demo deadlock

### ISSUE THREAD

**Issue by jvermillard** [eclipse/leshan#217]
Observed on leshan.eclipse.org, see the attacked thread dump
[jstack.txt](https://github.com/eclipse/leshan/files/646753/jstack.txt)

Memory dump:
[dump.bin.gz](https://github.com/eclipse/leshan/files/646767/dump.bin.gz)

**Comment by sbernard31** [comment]
I find some suspicious `synchronized` block.
 - [`client.getLifeTimeInSec`](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/client/Client.java#L224)
 - [`Cleaner.run`](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/InMemoryRegistrationStore.java#L430)

But I can not use the thread dump for blaming them :-/

**Comment by sbernard31** [comment]
The issue is probably because we try to acquire writelock as a reader in the `Cleaner`.
The doc say : [_"upgrading from a read lock to the write lock is not possible."_](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html)

I fixed it in commit (a2fb1e26208fe90345931c54447af048c0e30e6e)
I also removed the suspect `synchronized` block.
