### ISSUE TITLE
support new Content-Format code for TLV/Json 

### ISSUE THREAD

**Issue by jvermillard** [eclipse/leshan#225]
https://www.iana.org/assignments/core-parameters/core-parameters.xhtml

application/vnd.oma.lwm2m+tlv 		11542 	[OMA-TS-LightweightM2M-V1_0]
application/vnd.oma.lwm2m+json 		11543 	[OMA-TS-LightweightM2M-V1_0]

Of-course we should continue to support the old ones

**Comment by sbernard31** [comment]
Done

**Comment by drugo72** [comment]
> Of-course we should continue to support the old ones
I'm curious why the old 1542 (tlv) and 1543 (json) codes will still be supported while support for 1541 (replaced by text/plain) has gone.

**Comment by sbernard31** [comment]
I didn't even remember this code was existed. It seems the code was changed 1 years ago.
Did you need this code ? I can add it or you can propose a PR if this is necessary.

**Comment by cdealti** [comment]
The Contiki OS lwm2m implementation is still using that code and it needs to be updated to work with the latest Leshan.
From the IANA links above I see that the old 1542 and 1543 codes are still reserved to lwm2m but this is not the case for 1541. I guess there is a reason for this and I was just curious what this reason is or why the standard ``text/plain`` code was not used at that time.
It's up to you if you still want to support 1541, I've already filed an issue to Contiki so it's likely they will upgrade to the standard ``text/plain`` Content-Format.

Thanks!

**Comment by sbernard31** [comment]
I think this is because at the begining there wasn't code value in the spec. So implementers chose a value arbitrary. Then OMA propose to use `text/plain` for text (code 0). Then OMA decide to register value for json and tlv, they propose to use 1542,5143 as implementation already used it, but this value was in range reserved for CoAP. It was proposed to provide different numbers (11542 and 11543) and keep the two original numbers (1542 and 1543) unreserved and tagged as "do not use".

**Comment by cdealti** [comment]
Thanks for the answer. Then I think you don't need to continue supporting 1541 unless someone else complains about it.
