### ISSUE TITLE
Question on External Database Model

### ISSUE THREAD

**Issue by nginxsantos** [eclipse/leshan#229]
Is there any plan to support an external Database model?

**Comment by jvermillard** [comment]
you can implement your own store for security keys or for storing registration.
What do you mean exactly by "external Database mode" ?

**Comment by nginxsantos** [comment]
Hi @jvermillard ,

Thank you for your response.

I was asking if it supports the information to be stored in external DB and as per your clarification the answer is YES. Thanks.

You mentioned the current support is REDIS and some interest was there for MongoDB, I was also looking for a MongoDB support. Is there any official patch for this. I will definitely submit a patch if I think of some other Database.

Could you also please clarify if it is completely stateless model? 

What part of information gets stored in DB and what part of information gets stored in Memory.

Thanks in advance.

Wishing you a very happy new year 2017.

Thanks, Santos

**Comment by jvermillard** [comment]
Some details here: https://github.com/eclipse/leshan/wiki/Cluster

There is no official mongodb support now, maybe in the future, we would be very happy to help you if you want to contribute something like that :)

The DTLS session is not stateless, a lot of state are in memory, and also sort CoAP request/response should happen on the same node but outside of that it's stateless for long lasting requests (observations).

**Comment by nginxsantos** [comment]
Hi,


Thank you. I will definitely contribute if I develop the support for Mongo
DB.

Regarding redis, does  it support "regular redis" or "redis-cluster". I
think regular Redis is like memcached, there is no redundancy built into it
– all redundancy needs are therefore pushed up into application space
(i.e., pushing to 2 memcached’s, always).  So, I am trying to understand
does it support redis-cluster?

Thanks, Santos

**Comment by jvermillard** [comment]
I should support redis cluster/sentinel, you maybe have o modify the way the redis (jedis) client is configured

**Comment by nginxsantos** [comment]
Hi,

Is there any roadmap defined for Leshan. I want to take a look and would
like to see if I can contribute on something.

On the database, as you mentioned the  keys, sequence numbers, etc. for a
session kept in the database,  I’ll assume that if the leshan-server dies,
the affected devices does not need to re-establish a DTLS session and
another can immediately take over. Is my assumption correct ?

Regards, Santos

**Comment by sophokles73** [comment]
Hi Santos,

I have made some comments inline ...
-- 
Mit freundlichen Grüßen / Best regards

Kai Hudalla
Chief Software Architect

Bosch Software Innovations GmbH
Schöneberger Ufer 89-91
10785 Berlin
GERMANY
www.bosch-si.com

Registered office: Berlin, Register court: Amtsgericht Charlottenburg,
HRB 148411 B;
Executives: Dr.-Ing. Rainer Kallenbach, Michael Hahn

On Tue, 2017-01-03 at 07:58 -0800, nginxsantos wrote:
> Hi,
> 
> Is there any roadmap defined for Leshan. I want to take a look and would
> like to see if I can contribute on something.
> 
That would be great :-)

> On the database, as you mentioned the keys, sequence numbers, etc. for a
> session kept in the database, I’ll assume that if the leshan-server dies,
> the affected devices does not need to re-establish a DTLS session and
> another can immediately take over. Is my assumption correct ?
> 
In general, your assumption is correct. However, the DTLS session fail-over is
handled at the Californium level (the CoAP implementation used by leshan).
Californium's Scandium module is responsible for establishing and managing the
DTLS sessions. By default, all session information is kept in-memory only.
However, you can provide an implementation of the "SessionCache" interface to
persist an established session's security parameters to e.g. Redis or a database.
 In the fail-over case another leshan instance can then do an "abbreviated
handshake" with the client, i.e. the client does not need to do a full DTLS
handshake again with the server but can "resume" the existing session.

**Comment by nginxsantos** [comment]
Hi Kai,

Many thanks for your input - I thought so by reading the description
https://github.com/eclipse/leshan/wiki/Cluster

But, I think you have decided not to implement DTLS resume for performance
gain. Would you please clarify how much hit/impact you expected if some one
implements this? I am just trying to evaluate the pros and cons

>>> For a first step DTLS resume can be excluded because we can force the
client into a full re-handshake (which is not so costly with PSK schemes).

Is there any study of the Leshan performance analysis, could you kindly
share the same.

Regards, Santos

**Comment by sbernard31** [comment]
Hi, 

**About persistency :**
At Leshan side, [security][1] and [registration/observation][2] data can be store in external DB.

About DTLS session, by default nothing is persisted. The `SessionCache` for DTLS is currently not available in the Californium version we depend on. As Kai said this will just allow you to do resume handshake instead of fullhandshake. For PSK schemes bandwidth gains are negligible.

The rest is store in memory.

To be clear if you restart Leshan, you lost : 
    -  DTLS information (session+connection)
    -  all CoAP block1 or block2 pending exchanges.
    -  all pending requests. (If you receive a response of request sent before restart we will not be able to handle it)
Registrations and observations are kept.

[1]:https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/security/SecurityStore.java
[2]:https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/registration/RegistrationStore.java

**About Clustering**
Leshan cluster is really experimental (never really tested). It will probably not be available in the first release of Leshan. Help is welcomed :)

About redis clustering, our current implementation support only one redis instance. see redisLock [here][3] and [here][4].

[3]: https://github.com/eclipse/leshan/blob/master/leshan-server-cluster/src/main/java/org/eclipse/leshan/server/cluster/RedisLock.java
[4]: http://redis.io/topics/distlock#correct-implementation-with-a-single-instance

**About release plan**
 You can find some information about that on the [mailing list][5]

[5]:https://dev.eclipse.org/mhonarc/lists/leshan-dev/msg00631.html

**Comment by nginxsantos** [comment]
Hi,

Thank you for all the clarification. It is really helpful.

Now, I am pretty much clear on what is available and what needs to be done.
Most likely I will pick up the cluster testing and see....

>>The SessionCache for DTLS is currently not available in the Californium
version we depend on

Not able to find the roadmap for this.

Thanks, Santos
