### ISSUE TITLE
Wrong data type for resource 5701 in models

### ISSUE THREAD

**Issue by dnav** [eclipse/leshan#349]
In leshan-server-demo/src/main/resources/models, the reusable resource 5701 (Sensor Unit) is defined as a `Float` instead of a `String` in xml files:
- 3300.xml
- 3316.xml to 3330.xml
- 3346.xml

(You can use the command `git grep -A 5 5701` to check.)

**Comment by sbernard31** [comment]
We used this URL to update our models : http://www.openmobilealliance.org/wp/OMNA/LwM2M/DDF.xml

And it points to : 
http://www.openmobilealliance.org/tech/profiles/lwm2m/3300.xml
http://www.openmobilealliance.org/tech/profiles/lwm2m/3330.xml
http://www.openmobilealliance.org/tech/profiles/lwm2m/3316.xml
http://www.openmobilealliance.org/tech/profiles/lwm2m/3346.xml
where `Sensor Unit` is a float.

I will fix this in Leshan demo because a sensor unit typed as float doesn't make sense. but we should also report that to OMA (else next time we will update models we risk to introduce this bugs again)

**Comment by sbernard31** [comment]
@dnav did you notify OMA about that ?

**Comment by sbernard31** [comment]
https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/212 looks like to our issue here.
