### ISSUE TITLE
Server initiated bootstrap mode

### ISSUE THREAD

**Issue by Muthuiot** [eclipse/leshan#410]
Hi,

I would like to understand server initiated bootstrap mechanism with Leshan. Need help on this.

**Comment by sbernard31** [comment]
This is not implemented. see https://github.com/eclipse/leshan/wiki/Supported-features

**Comment by sbernard31** [comment]
(not planned a short/mid term)

**Comment by sbernard31** [comment]
Server Initiated was not clearly define in LWM2M 1.0.
Since [LWM2M v1.1 server initiated](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-3-4-0-6134-Server-Initiated-Bootstrap) is specified and can be achieved  through resource 1/x/9 Bootstrap-Request Trigger.

This is now implemented since : d9ae7bb8df91bf0279f418a868712ac130a7c3b7  _Implement "Bootstrap-Request Trigger" resource (1/?/9) at client side._
(and so available in Leshan v2.0.0 since v2.0.0-M4)

The spec also says that : 

> Note: proprietary mechanisms can be used to cause a LwM2M Client to enter the standard "Client Initiated Bootstrap" mode, but that is outside the scope of this specification.

And so this is also out of Leshan scope but anybody can implement it by calling LwM2mClient.triggerClientInitiatedBootstrap(boolean)`
