### ISSUE TITLE
Migrating from leshan-0.1.11-M12 to 1.0.0

### ISSUE THREAD

**Issue by AlexITC** [eclipse/leshan#420]
I have been migrating code that is using `leshan-0.1.11-M12` and need to confirm some of my findings.

1. We implemented the old `ClientRegistry` interface where we were storing the listeners for the clients (`ClientRegistryListener`), now this logic has been moved to `RegistrationService` interface having `RegistrationServiceImpl` implementing the logic for triggering the events to the listeners, I've seen that `RegistrationHandler` is firing these events as well as handling the registrations.
Q. Do I still need to maintain these listeners as well as the logic for triggering the events? My current answer is no.

2. Before, `ClientRegistry` contained very simple logic (maintain clients and listeners), now the listener logic is gone but we need to implement `CaliforniumRegistrationStore`, hence `RegistrationStore` (Leshan) and `ObservationStore` (Californium), I would be handling the registrations and planning to delegate the Leshan Observation logic to `InMemoryRegistrationStore`, and delegate Californium Observation logic to `InMemoryObservationStore`.
Q. Is there any idea against doing this?

3. Is there any breaking change with Leshan Cluster? I haven't seen anything until now.

Any advice would be appreciated.

Links:

Old version:
- [leshan-0.1.11-M12](https://github.com/eclipse/leshan/tree/leshan-0.1.11-M12)
- [ClientRegistry](https://github.com/eclipse/leshan/blob/11e758050e8a11e8abb1d70878fdcd0104e1d56a/leshan-server-core/src/main/java/org/eclipse/leshan/server/client/ClientRegistry.java)
- [ClientRegistryListener](https://github.com/eclipse/leshan/blob/11e758050e8a11e8abb1d70878fdcd0104e1d56a/leshan-server-core/src/main/java/org/eclipse/leshan/server/client/ClientRegistryListener.java)

Current version:
- [RegistrationService](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/registration/RegistrationService.java)
- [RegistrationServiceImpl](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/impl/RegistrationServiceImpl.java)
- [RegistrationHandler](https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/registration/RegistrationHandler.java)
- [CaliforniumRegistrationStore](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/CaliforniumRegistrationStore.java)

Thanks!

**Comment by sbernard31** [comment]
ClientRegistry and ObservationRegistry was replaced by CaliforniumRegistrationStore.

CaliforniumRegistrationStore is just a "store" and don't need to handle listener anymore this is now done by internal Leshan classes (RegistrationHandler+RegistrationService)

(Californium)RegistrationStore handle now observation+registration, it aims to be able to do some operation in an atomic way. That's because registration and observation lifetime is tied.

So to be clear :
1) No, you don't need to handle all the listener stuff.
2) I'm not sure this will work, registration and observation is really tied. E.g. when you remove a registration you need to remove all the related observations. I don't know how you can do that by delegating. Could you detail your use case where you need a custom implementation to persist registration and you could reuse InMemoryStore for observation ?

**Comment by AlexITC** [comment]
About CaliforniumRegistrationStore, I would implement all methods like `addRegistration`, `removeRegistration`, `getBy...`, then, I create an `InMemoryRegistrationStore` that's used by the methods related to Leshan Observation like `addObservation`, `removeObservation`, etc.

A simple example would be like this (Scala):
```scala
  private val leshanObservationStore = new InMemoryRegistrationStore()

  override def removeRegistration(registrationId: String): Deregistration = {
    // my logic
    removeObservations(registrationId)
  }

  override def removeObservation(registrationId: String, observationId: Array[Byte]): LeshanObservation = {
    leshanObservationStore.removeObservation(registrationId, observationId)
  }
```

Californium `ObservationStore` methods would be implemented in a similar way using `InMemoryObservationStore`.

Thanks.

**Comment by sbernard31** [comment]
This is a more detailed explanation of what you want to do technically.
I asked more about the use case behind this ? how/where do you store registration in your custom logic ? Why observation stuff could be reused and registration stuff not ?

But to answer again, I afraid this will not work because as I said : Registration and Observation lifetime is tied. More you will lost all the lock/atomic stuff.
You could try but I don't advice this.

**Comment by AlexITC** [comment]
That's exactly what I wanted to know, thanks!
