### ISSUE TITLE
Client registration update should contain only parameters which changed.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#434]
Currently registration update is empty, it just aims to "refresh" registration.

The spec §5.2 say : 
_"This “Update” operation MUST contain only the parameters (lifetime/binding mode/ SMS number/ objects and objects instances) which have changed compared to the last registration parameters sent to the LwM2M Server "_

**Comment by NayangiriGoswamiGit** [comment]
"Currently registration update is empty, it just aims to "refresh" registration."
By this statement, should I consider that if Leshan client  add custom/new object and call triggerRegistrationUpdate() method on client object, the newly added object will not available at server side.

Because, I tried something like this
`builder.setAdditionalAttributes(additionalAttributes);
		LeshanClient client = builder.build();
		client.start();
		Thread.sleep(10000);
		initializer.setInstancesForObject(32767, new RandomTemperatureSensor());
		builder.setObjects(initializer.create(7,32767,LwM2mId.SECURITY,LwM2mId.SERVER, LwM2mId.DEVICE));
		client.triggerRegistrationUpdate();
		System.out.println("update triggered");`
But on leshan -server-demo UI in browser I'm not able see newly added object, which is 32767.
Thanks

**Comment by sbernard31** [comment]
> By this statement, should I consider that if Leshan client add custom/new object and call triggerRegistrationUpdate() method on client object, the newly added object will not available at server side.

Exactly, not supported for now.

> Because, I tried something like this

So, this will not work :confused: .
Just to let you know, if/when we will implement a way to "add new object", this will not be available using `builder` (Builder is just to initialize client, once client is created you don't use `builder` anymore)

**Comment by sbernard31** [comment]
@NayangiriGoswamiGit  I created new PR about that #787 #788

**Comment by sbernard31** [comment]
This is now integrated in master (#787)
