### ISSUE TITLE
Question about denying registration

### ISSUE THREAD

**Issue by AlexITC** [eclipse/leshan#456]
While upgrading from `leshan-0.1.11-M12` to the latest version, one of the changes is that previously the [ClientRegistry#registerClient](https://github.com/eclipse/leshan/blob/leshan-0.1.11-M12/leshan-server-core/src/main/java/org/eclipse/leshan/server/client/ClientRegistry.java#L63) method could return `false` to deny a registration, in this case, the `RegistrationHandler` would just return `RegisterResponse.forbidden(null)`.

Now, `ClientRegistry#registerClient` is `RegistrationStore#addRegistration` which just assumes that the registration could always be created, `RegistrationHandler#register` method doesn't handle any exception which is the only way to deny the registration.

My understanding, is that all this logic to deny a registration should be added implementing a custom `Authorizer`, is this assumption correct?

Thanks.

**Comment by sbernard31** [comment]
**Short answer :**  your assumption is correct.

**Long answer :** We decide to refactor `ClientRegistry` to make "a real store" with the only responsibility to store data. We decide to move out listeners and authorization responsibility. We keep expiration as this could be link to the store.
We also detect that observation and registration store should be merged because their lifecycle is linked and we need atomic modification which impact both. This merge make the RegistrationStore a bit complex. Removing authorization responsability is also a way to limit this complexity.

Is the new API ok ? or Does it bring issues ?

**Comment by AlexITC** [comment]
great! the new API is better in my opinion.

thanks.

**Comment by sbernard31** [comment]
Good to hear !
