### ISSUE TITLE
Leshan Server UQ and UQS modes

### ISSUE THREAD

**Issue by bahmank1** [eclipse/leshan#457]
Does the latest version of Leshan support UQ and UQS modes?
Our application requires for the server to queue up device commands while the device is unavailable and send the command(s) when Register Update Trigger is received. 
If yes, where can I find the info/code?
If not, does anyone have an implementation that is willing to share? 

Thanks,
bahman

**Comment by sbernard31** [comment]
I suppose you are talking about server side.
There isn't  version of Leshan with Queue mode available. (see [wiki](https://github.com/eclipse/leshan/wiki/LWM2M-Supported-features))
Queue mode is currently in development. (see #455), but the first version will not implement a queue but just a way to be aware of the client state (Sleeping/awake) (see #427)

**Comment by sandeepakhouri** [comment]
In addition to this, the S mode (SMS) is not supported, as Leshan only supports UDP binding.

**Comment by bahmank1** [comment]
So Leshan server only support U and UQ where:
1) in U mode, the device is listening while it is awake but does not inform the server when it comes in and out of power save more.
2) in UQ mode device informs Leshan server of its sleep/awake states, Leshan server remembers this state for each device. Now, if the application server has a message to send to the device, does it need to first ask Leshan if the device is awake and then send it, or it just sends it to Leshan and if the device happens to be in sleep mode, Leshan rejects the message. Will Leshan know when a device is coming back online?

**Comment by carlosgp143** [comment]
The Q-Mode is being implemented right now, you can see it in the [queue_mode](https://github.com/eclipse/leshan/tree/queue_mode) branch and in the PRs #461 and #455. 

For now the idea is that the application server can register a listener that is informed by Leshan when the client state changes to awake or sleeping. So the application should only try to send when the state is awake, and if it tries to send a message when the client is sleeping, it will be rejected by Leshan. In the future, the idea is probably to have an queue so that Leshan can store requests and send them when the client is awake again. 

And yes, Leshan knows when the device is online because it sends a registration update message. And for controlling the sleeping state, a timer is used, see #455 .

**Comment by sandeepakhouri** [comment]
Queue Mode should not be confused with an online/offline status that needs to be queried. It is a fair assumption that the device is ALWAYS sleeping. When the device wakes up, it sends a registration update to the server. The server than has the window of opportunity to communicate with the client before it goes back to sleep based on MAX_WAIT_TIME. 
Therefore, polling to query the status or server remembering state can be avoided.

**Comment by sbernard31** [comment]
I think we can close this one.
(feel free to reopen it if I'm wrong)

**Comment by sbernard31** [comment]
The first version of QueueMode support at server side is available in #469  and soon integrated in master.
