### ISSUE TITLE
Ongoing request is not canceled on deregistration

### ISSUE THREAD

**Issue by danielhqv** [eclipse/leshan#503]
Looking into the code, there doesn't seem to be any exposed way to cancel an ongoing request?

Our scenario is that we're transferring a FOTA image, which may take several minutes, and sometimes we get a deregistration from the device during this, but the write request continues running in the background, eventually resulting in a success or timeout.

We would like to be able to cancel the ongoing request as soon as the deregistration occurs.

Thx!

**Comment by sbernard31** [comment]
You're right there is no API to cancel a request.

For your use case, this should work like you expect as pending request should be canceled in deregistration.

See : https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/LeshanServer.java#L156

So you probably find a bug we should investigate this.

**Comment by sbernard31** [comment]
I think I find the issue. I created a PR #521.
Could you check if this behave better ?

**Comment by sbernard31** [comment]
@danielhqv Do you think you could find time to check if the PR #521 fix your issue ?

**Comment by danielhqv** [comment]
I've had a look now, but I'm sorry to say that I don't think I'm able to ascertain whether this would help me or not. I have no reproducable test to simulate this sudden unregistration that we sometimes see in real life situations, where a successful WriteResponse may turn up in the logs long after the device has unregistered and perhaps even established a new registration in the meantime.

But I didn't think that this was only a Leshan issue? How does the Californium BlockwiseLayer class get aware that it shouldn't send the next block but instead cancel the request? I cannot find that logic in the code.

**Comment by sbernard31** [comment]
Californium have 2 way to handle block transfer, "transparent" and "manual".

Leshan use the transparent one. 
In this mode when you send a request with a big payload it is "changed" in several block request.

At californium level, only the "high level request" can be handled by the user. When he cancel this request, this should cancel the block exchange related.

This is complex part of the code but I believe that cancel the request will complete the exchange which hold the "high level request" and all the "block requests".

The is a [test](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/test/java/org/eclipse/californium/core/test/lockstep/BlockwiseClientSideTest.java#L1119) which check this in californium.

I believe it's ok at californium side.

At leshan side, we try to cancel all ongoing request at registration. The initial goal was to avoid retransmission. And so there is a kind of optimization around acknowledgement. (if we receive the ack we can remove it from request to cancel on de-registration). But without going to deep this does not works for transparent block transfer so this is safer to wait for response before to clean instead of ACK.

So to conclude, I think this should fix your issue.
I will wait a little bit but if you can confirm this fix it easily I will integrate #521 in master.

**Comment by sbernard31** [comment]
I integrated #521 in master.
So I will close this issue. Please reopen it, if the problem still occurs.
If it is fixed for you, let us know by commenting here :pray: 
Thx again @danielhqv for your contribution.
