### ISSUE TITLE
Read, Write, Execute method of Security object in leshan-client-demo was not called after a bootstrap

### ISSUE THREAD

**Issue by chuchiliusandc** [eclipse/leshan#522]
Hi,

I am confused here.
I populated the certificate in leshan-server-bs and respond according to bootstrap request ...
However, the leshan-client-sim's Security object constructor, read, write methods are not triggered.
Does leshan-client-sim really save the certificate ?

Thanks :)

**Comment by sbernard31** [comment]
What do you call `leshan-server-sim` ? I suppose you are talking about `leshan-server-demo`.

Anyway for now Leshan does not really support X509(#436) and RPK(#435) at client side, but `write` method in `Security` object should be triggered...

**Comment by sbernard31** [comment]
@chuchiliusandc, good catch about the variable issue.

And you're right too about this method was never called after a bootstrap.

That was because a SimpleInstanceEnabler was created instead of Security object.

**Explanation:**
Via initializer, you can create a factory for each object to make leshan-client able to create new instance. To do that you can use setFactoryForObject or setClassForObject (in this case the class should have an empty constructor and the factory will just call it) or setInstancesForObject.

For the last method this set the initial instances and create a factory which use the default/empty constructor of the class of the instance or a dummy factory which will create dummy SimpleInstanceEnabler.

At bootstrap time, initial instance of Security and Server was deleted, then new instance was created. As Server/Security does not have default empty constructor, a SimpleInstanceEnabler was used. (you could check this by adding logs in this class)

I fixed those 2 issue in #523. You could check if this behave better now.
But anyway X509 support at client side is still not implemented :/

**Comment by chuchiliusandc** [comment]
Got it. Thanks @sbernard31  :)
