### ISSUE TITLE
Server RegistrationHandler: Multiple register packets, but same identity

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/leshan#525]
While using a test setup that doubles/delays udp packets, I noticed, that https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/registration/RegistrationHandler.java#L55 does not handle the case of two identical register requests.

What happens is:
* New registration: [identity=Identity /192.168.1.17:12873[psk=publicid], registrationEndpoint=0.0.0.0/0.0.0.0:5684, lifeTimeInSec=100, lwM2mVersion=1.0, bindingMode=U, endpoint=screenControl, registrationId=**ohR9MVoozR**, objectLinks=...]
* New registration: [identity=Identity /192.168.1.17:12873[psk=publicid], registrationEndpoint=0.0.0.0/0.0.0.0:5684, lifeTimeInSec=100, lwM2mVersion=1.0, bindingMode=U, endpoint=screenControl, registrationId=**UXgnGtgGtD**...]

So everytime a new registrationId is assigned. That lead to the situation that server and client communicated happily until `lifeTimeInSec` was over and a registration update was due. The client got **ohR9MVoozR** confirmed as server object location (`/rd/ohR9MVoozR`) and tries to update with this first assigned regID.

The server doesn't know anymore about this regID and answers with a 404:
```java
Registration registration = registrationService.getById(updateRequest.getRegistrationId());
if (registration == null) {
     return new SendableResponse<>(UpdateResponse.notFound());
}
```

Is there any reason why `RegistrationHandler.register` does not check the `registrationService` for a current known ID of the given `Identity` and assigns the same registrationID again?

**Comment by sbernard31** [comment]
If I well understand you would like that a re-registration reused the registration ID of the previous registration.

I think this is not the way the specification define this scenario.

The [specification](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf)  (§5.3.1 Register) say : 
_"If the LwM2MClient sends a “Register” operationto the LwM2MServer even though the LwM2MServer has registration information of the LwM2MClient, the LwM2MServer removes the existing registrationinformationand performs the new “Register” operation. This situation happens when the LwM2MClient forgets the state of the LwM2MServer (e.g., factory reset)."_

I don't  always totally agree with the specification, but this time this makes sense to me.

Do you have a real life scenario which bring you to this question ?

**Comment by davidgraeff** [comment]
The scenario is a duplicated register packet (which might happen on udp). I'm using the wakaama client code and the client happily communicates with the server but has a wrong idea of what the actual  registration ID is and therefore the next registration update fails. 

It should not happen that the client and server registration id differ and the session is still established. Is this a wakaama issue or not handled in the lwm2m specification?

**Comment by davidgraeff** [comment]
Might be a bug in wakaama. It is not an error on the coap protocol level or on leshans side, so I'm closing this issue.

There are two registration messages with different coap message ids on the wire. So leshan is doing everything according to the spec (by issuing two different registration IDs). But the wakaama client apparently accepts the ACK of the first message and is ignoring the second ACK.

The wakaama client and leshan server are happily communicating after this basically failed handshake until leshan discovers that it doesn't know the client as soon as a re-registration is due.
