### ISSUE TITLE
Couldn't connect to the live test servers

### ISSUE THREAD

**Issue by YTTsai2013** [eclipse/leshan#526]
Are the servers down in these two days? I couldn't open the following web pages. Thanks!

http://leshan.eclipse.org/
http://leshan.eclipse.org/bs/

**Comment by sbernard31** [comment]
We reinstalled the sandox server yesterday. (because the linux distrubution was not maintained anymore) 
But It should be ok since yesterday around 05:00 pm (UTC+2).

However, this time we configure the sandbox to use https.

So the new url are :
https://leshan.eclipse.org/
https://leshan.eclipse.org/bs/

I just tested,and it works for me.

**Comment by sbernard31** [comment]
There was an issue with the http to https redirection. I just fixed it. So this should behave better now.

**Comment by YTTsai2013** [comment]
The servers are working now, but I have another question. Is it possible to change the security mode of the bootstrap server? It seems to be fixed as no security.

**Comment by sbernard31** [comment]
There is no UI in the bootstrap server demo to do that, but you could use the rest API.
https://github.com/eclipse/leshan/issues/374

I never tested this script with https... let me know if it works?

**Comment by YTTsai2013** [comment]
Sorry, I don't have time to try the method in #374 recently, but you could close this issue.  Thanks for your support.
