### ISSUE TITLE
change the registration and obs in ObservationListener?

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/leshan#544]
May I change the registration and obs while recieving a observ response.

In NB-iot,sometimes the device's ip and port maybe changed if no corresponde for a long time.
so I want change the  registration and obs   while recieving a observ response everytime.

**Comment by sbernard31** [comment]
Hi,

In LWM2M there are 2 mode. 
 - U(UDP) which is adapted to use case where devices use a fixed/static IP address/port.
 - UQ(UDP with Queue Mode) which is adapted for environment where devices use dynamic address/port (like NAT environment)

Generally, if you have dynamic device address/port, you are in device initiated communication mode because server could not know the address/port of the device at every moment. (The address/port store in the registration could be obsolete)

 If you are in queue mode, each time you "wake up" and go back to communicate with the server, you should start by an update so in this case you don't really need to update registration on "observe response".

What I try to explain here is that the use case your express here seems a bit of of LWM2M specification.

If you really want to do that knowing that maybe you will lost the benefits of interoperability.
You could try to add a notification listener like this :

```java
lwServer.getObservationService().addListener(new ObservationListener() {
            @Override
            public void onResponse(Observation observation, Registration registration, ObserveResponse response) {
                // Update client with the new address/port
                Response coapResponse = (Response) response.getCoapResponse();
                Identity obsIdentity = EndpointContextUtil.extractIdentity(coapResponse.getSourceContext());

                if (!registration.getIdentity().equals(obsIdentity)) {
                    LOG.error("Observation with invalid identity. Expected {} but was {}", registration.getIdentity(),
                            obsIdentity);
                }

                // Create a fake registration update
                RegistrationUpdate regUpdate = new RegistrationUpdate(registration.getId(), obsIdentity, null, null,
                        null, null, null);

                // Get the store (maybe you can access to it in a proper way (e.g. if you implement your own store)
                RegistrationStore store = ((RegistrationServiceImpl) lwServer.getRegistrationService()).getStore();

                // Update registration
                store.updateRegistration(regUpdate);
            }

            @Override
            public void onError(Observation observation, Registration registration, Exception error) {
            }

            @Override
            public void newObservation(Observation observation, Registration registration) {
            }

            @Override
            public void cancelled(Observation observation) {
            }
        });
```

**Comment by sbernard31** [comment]
Here an old discussion about that : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/115

I re-read it and re-read the last version of the specification and still not sure what is the right way.
So I asked this question again : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/391

**Comment by bujingyun8** [comment]
Thank you very much.
In my case,the device's port will changed if no communication for about 5-10 minutes
because  our  devices behind telecoms operat‘s NAT

so I want to change the port stored in redis when recieving sth from device every time.
just do this is enough？

**Comment by sbernard31** [comment]
> so I want to change the port stored in redis when recieving sth from device every time.

This will change port only for notification.

**Comment by sbernard31** [comment]
(notifications + the default port changed on update)

**Comment by sbernard31** [comment]
Could we close this issue ?

**Comment by bujingyun8** [comment]
of course,thank you very much
