### ISSUE TITLE
write package_url in JSON format produce wrong data

### ISSUE THREAD

**Issue by lianzeng** [eclipse/leshan#557]
i'm now integrate lwm2mclient with leshan server, and try to write URL to client via /5/0/1 using JSON format, and the captured data is "{"bn":"/5/0/1","e":[{"n":"","sv":"http"}]}"   ,which cause client parse failed,
i think the data should be           "{"bn":"/5/0/1","e":[{"n":"1","sv":"http"}]}"   , which can be parsed by client.
so will it be fixed ?

**Comment by sbernard31** [comment]
The LWM2M2 specification 1.0.2 says : 
```
Each entry of the JSON format is a Resource Instance, 
where the Name attribute need to be prepended by the Base Name
attribute to form the unique identifier of this Resource instance.

The Name attribute in of this array entry is a URI path relative to the Base Name;
namely the Name attribute could simply be
the full URI of a requested Resource Instance when Base Name is absent."
```

So, It seems clear to me that the proposed behavior :  "{"bn":"/5/0/1","e":[{"n":"1","sv":"http"}]}" is not valid. (in this case that means that the URI is /5/0/1/1)

About, the current behavior, "{"bn":"/5/0/1","e":[{"n":"","sv":"http"}]}",  It seems to be valid. I would say this is a device issue, which implementation are you using ?

Reading the SENML draft referencing by the LWM2M spec : 
```
Name
 
Name of the sensor or parameter.  When appended to the Base Name
attribute, this must result in a globally unique identifier for
the resource.  The name is optional, if the Base Name is present.
If the name is missing Base Name must uniquely identify the
resource.  This can be used to represent a large array of
measurements from the same sensor without having to repeat its
identifier on every measurement.
```
This reinforce that base name could be absent or even empty.

**Comment by lianzeng** [comment]
hi,  sbernard31,
thanks for you reply, i use the wakama(https://github.com/eclipse/wakaama) as lwm2m client , and parse failed if the payload is "{"bn":"/5/0/1","e":[{"n":"","sv":"http"}]}"  ,  how do you think if the content change to be  "{"bn":"/5/0","e":[{"n":"1","sv":"http"}]}"  , will it be easier for understanding ?

**Comment by sbernard31** [comment]
> how do you think if the content change to be "{"bn":"/5/0","e":[{"n":"1","sv":"http"}]}" , will it be easier for understanding ?

I do not exclude the possibility to change leshan json encoder but I feel if this is allowed by the specification this should be fixed in wakaama instead of changing encoding in Leshan.

What happens if someone else open a bug here because its client does not support "{"bn":"/5/0","e":[{"n":"1","sv":"http"}]}"  and it prefer "{"bn":"/5/0/1","e":[{"n":"","sv":"http"}]}" ?

Did you try to open a issue at https://github.com/eclipse/wakaama/issues/378 ?

If you want a shortterm/fast solution at Leshan side, you can replace the current jsonencoder. See explanation [here](https://github.com/eclipse/leshan/issues/562#issuecomment-418118252) some hint to do that.

**Comment by sbernard31** [comment]
It seems this will be fixed in wakaama : https://github.com/eclipse/wakaama/pull/392

**Comment by sbernard31** [comment]
I think we can close it as there is no issue at Leshan side and  wakaame seems to go for a fix.
