### ISSUE TITLE
Leshan client doesn't send response to bootstrap finish message in all cases (race condition)

### ISSUE THREAD

**Issue by lhotari** [eclipse/leshan#589]
There's currently a race condition in the Leshan client related to bootstrapping. In some cases, bootstrapping fails from the server's perspective with `BootstrapFailureCause.SEND_FINISH_FAILED`. The server doesn't receive a reply to the bootstrap finish message. 

The easiest way to explain the issue is to show the code:
https://github.com/eclipse/leshan/blob/fbc01b848043cd4c8605bbd1d566728026300bbd/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/BootstrapHandler.java#L50-L64

The latch gets released before the response is sent to the server. 

I'd assume that the fix would be to release the latch after the response has been sent in `BootstrapResource` class (assuming `exchange.respond` is synchronous):
https://github.com/eclipse/leshan/blob/fbc01b848043cd4c8605bbd1d566728026300bbd/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/impl/BootstrapResource.java#L42-L50

the race condition currently (in 1.0.0-M9) happens when the endpoint gets destroyed after bootstrapping finishes from the clients perspective:
https://github.com/eclipse/leshan/blob/fbc01b848043cd4c8605bbd1d566728026300bbd/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/impl/CaliforniumEndpointsManager.java#L65-L70

that gets called from
https://github.com/eclipse/leshan/blob/fbc01b848043cd4c8605bbd1d566728026300bbd/leshan-client-core/src/main/java/org/eclipse/leshan/client/servers/RegistrationEngine.java#L175-L180

**Comment by lhotari** [comment]
Looks like the latch could be released in a code block something like this in `BootstrapResource` class:
```
            Response responseMessage = new Response(toCoapResponseCode(response.getCode()));
            responseMessage.addMessageObserver(new MessageObserverAdapter() {
                @Override
                public void onSent() {
                    bootstrapHandler.markFinished(); // releases the bootstrappingLatch
                }
            });
            exchange.respond(responseMessage);
```
`exchange.respond` is asynchronous, so the `MessageObserver.onSent` callback would be the correct place to release the latch.

**Comment by sbernard31** [comment]
That's what I currently implement, I provide a PR soon.

**Comment by sbernard31** [comment]
Ok I created a PR #592.

I didn't test it so much because I have no more time today.
You could test it and see if it behave better (if you can reproduce the issue easily of course which is not always the case with race condition ...)

By the way this will change the behavior, because by the past  receiving a bootstrap finish request always stop the bootstrap.
Here if the response failed to be sent then you will go in bootstrap timeout.

**Comment by sbernard31** [comment]
I also think about that if that if the response of bootstrap finished is lost (because of UDP), then the server will try to send again the bootstrap finished request but as we will recreate new endpoints. The request will be not correctly handle by the client.

So maybe just for this request, client should ACK the bootstrapFinished request, then send the response as a CON. And instead of wait for response sending, we could wait for response acknowledgement ?

**Comment by sbernard31** [comment]
@lhotari  did you find time to test the PR? (or at least looking at it)

**Comment by sbernard31** [comment]
@lhotari, I finally decide to use separate response for bootstrap finished request.

I hope #592 will fix the issue you raise.

I integrated #592 in master so I will close this issue.

But please, do not hesitate to review this PR or share any feedback about it !

**Comment by lhotari** [comment]
Thank you @sbernard31 . I'm sorry I missed your previous requests for feedback. I'll let you know if there is any issues in the solution. I believe it's all ok, but I'll get it verified tomorrow
