### ISSUE TITLE
o & n cancel

### ISSUE THREAD

**Issue by anuscool** [eclipse/leshan#620]
I am trying to cancel observe for temperature sensor,this cancellation is happening only in leshan-server side(value updation stopped) but leshan server is not sending any command to cancel observe for client side.
From code it looks like sending command to lwm2m client is not implemented,is it true

@Override
    protected void doDelete(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String[] path = StringUtils.split(req.getPathInfo(), '/');
        String clientEndpoint = path[0];

        // /clients/endPoint/LWRequest/observe : cancel observation for the given resource.
        if (path.length >= 3 && "observe".equals(path[path.length - 1])) {
            try {
                String target = StringUtils.substringsBetween(req.getPathInfo(), clientEndpoint, "/observe")[0];
                Registration registration = server.getRegistrationService().getByEndpoint(clientEndpoint);
                if (registration != null) {
                    **server.getObservationService().cancelObservations(registration, target);**
                    resp.setStatus(HttpServletResponse.SC_OK);

**server.getObservationService().cancelObservations(registration, target);** is this command send any notification to lwm2m client to cancel observe.

**Comment by sbernard31** [comment]
There is 2 way to cancel an observation. active and passive one.
https://tools.ietf.org/html/rfc7641#section-3.6

Leshan implements only passive mode : https://github.com/eclipse/leshan/wiki/LWM2M-Supported-features#information-reporting

That's mean no request is sent. But next notification will be replied with RST message and will not be reported to application layer above.

**Comment by sbernard31** [comment]
The delete request is about HTTP and our REST API. (which is just a way to code a demo)
The standard say nothing about a REST API. (this is out of the spec)

At CoAP level, as I said above we don't support the active cancellation, so we don't send anything (and so we don't send GET+observe request)

Even if there is similarity between CoAP and HTTP, our demo is not a kind of proxy COAP(LWM2M)/HTTP.

About why we choose delete request ? because we see passive cancellation as removing an observation. From a REST point of view, we thought that makes sense (even if our API is clearly not a strict RESTful API)
