### ISSUE TITLE
Reason for Queue mode removal from Leshan.

### ISSUE THREAD

**Issue by zac7272** [eclipse/leshan#633]
Hi,

I'm working in a queue mode implementation for Leshan, and there was the implementation for same in the code but it was eliminated. I'm wondering what was the reason for this because I couldn't found any information about it.
I had gone through a similar discussion on this issue #427.

So the reason I could interpret are:
Leshan used an internal queue for pending requests, which was not flexible.
With the change in Lwm2m specs, OMA also dropped this mode and replaced with an offline/online mode

What change in Lwm2m specs resulted in dropping of Q mode and was there any other reason why it was dropped?
And What was lacking when it was implemented in the code ?

Regards

**Comment by sbernard31** [comment]
The "queue mode specification changes" say that implementation does not need to implement a "queue" but instead should provide mechanism which helps user to know if device is present or not.

The queue implementation in Leshan was dropped as we thought we was going on a wrong way.

But thanks to @carlosgp143  a new presenceService is now available in Leshan and I consider this is a good way to implement what the specification call "Queue Mode".

So queue mode was removed, but it was re-add since [leshan-1.0.0-M6](https://github.com/eclipse/leshan/releases/tag/leshan-1.0.0-M6).

**Comment by zac7272** [comment]
Thanks for the reply @sbernard31.
Is something still missing with the current implementation with Queue-Mode using presence service?
Does this implementation fully replicate with the original implementation of Queue mode? (which was removed in 2017)

**Comment by sbernard31** [comment]
I'm not sure what you mean by "fully replicate with the original implementation".
But the new implementation is different from the previous one ! From my point of view, the new one is better/clearer/more flexible, but you should store pending request by your self.

I suppose if you ask so many question about differences this is because you already use the old one. So just test it and let us know, if it's ok or if you have concrete issue.

**Comment by zac7272** [comment]
Thanks, @sbernard31 for clearing my doubt. I would surely test the previous version and get back on this.
Regards,
Palash

**Comment by sbernard31** [comment]
I would say "testing the new implementation"
