### ISSUE TITLE
NotSerializableException when trying to serialize Registration object

### ISSUE THREAD

**Issue by krisdx** [eclipse/leshan#647]
Hello, I'm doing some basic tests, trying to see ways to recover Registrations, after a server restart/failover, and when trying to write the Registration object to a file, I get:

java.io.NotSerializableException: org.eclipse.leshan.core.request.Identity

So can you tell me what I need to do, in order to Java serialize a Registration object?

**Comment by sbernard31** [comment]
To handle "server restart/failover" by persisting registrations in a file,  you need to implements your own `CaliforniumRegistrationStore`.

It could be a bit tricky but you could inspired yourself by looking at `InMemoryRegistrationStore` and `RedisRegistrationStore`

`RedisRegistrationStore` persists `Registration` in Redis, it uses `RegistrationSerDes` to serialize/deserialize `Registration` in JSON. Both classes could be reused.

About `java.io.NotSerializableException`, that means `Identity` is not serializable.
We don't use Java serialization anymore (I believe we used it a bit at the begin for testing/demo) that's why you can see `Registration` implements `Serializable` interface.

Java serialization is often considered as not well adapted for production use cases.
Frequent reasons exposed : 
 - this is slow (Personally I never test it and I don't know if our JSON serialization is faster)
 - bytes serialization is not easy for debug.
 - data migration after a schema modification (adding removing attributes) is hard to handle.
You could probably found more resources about that searching on the web.

Anyway, if you find java serialization adapted to your use case, I not really against trying to make it work in Leshan and to be honest currently the is not really clean to have `Registration` which implement `Serializable` with attributes which does not.

Did you try to just make Identity implements  `Serializable` ?

**Comment by krisdx** [comment]
I wasn't aware that you don't use Java serialization. So I'll either have to provide my own serialization/deserialization logic, or reuse RegistrationSerDes, witch I also wasn't aware of.
Ok, Thanks.

**Comment by sbernard31** [comment]
I will probably make `Identity` serializable so if someone want to use java serialization it will be able to do it.

**Comment by sbernard31** [comment]
I create a PR to make  `Registration` serializable again :  #649

**Comment by krisdx** [comment]
If you're going to support Java serialization, you should also think about making org.eclipse.leshan.core.observation.Observation and org.eclipse.californium.core.observe.Observation serializable, because they're all needed for the implementation of CaliforniumRegistrationStore.

**Comment by sbernard31** [comment]
@krisdx Good point ! I totally missed this part ...

Making `org.eclipse.leshan.core.observation.Observation` "serializable" is not really so hard but also not really useful as it is generally built from `org.eclipse.californium.core.observe.Observation` 
(see [InMemoryRegistrationStore](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M10/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/InMemoryRegistrationStore.java#L421))

But making  `org.eclipse.californium.core.observe.Observation` "serializable" is another story ...
Maybe we should reconsider my first idea to make it possible to use Java Serialization.

@boaks Do you have any opinion about that ?

**Comment by boaks** [comment]
A PR for californium would be welcome. 
Otherwise open an issue in californium.

**Comment by sbernard31** [comment]
@krisdx I feel making `org.eclipse.californium.core.observe.Observation` "serializable" will not be easy... 

We currently have a json serializer/deserializer, so maybe we should just back out making registration serializable again.

What did you do finally ? You are using `RegistrationSerDes` ?
Do you feel this is better to have a partial support of java serialization (I mean without `org.eclipse.californium.core.observe.Observation` or we should just remove it ?

**Comment by krisdx** [comment]
We've implemented the CaliforniumRegistrationStore by persisting only the Registrations in the DB. For the observations, we're just persisting info on what path an observation exists, and the actual org.eclipse.californium.core.observe.Observation objects are stored only at runtime, like in InMemoryRegistrationStore. When our server is restarted we re-initiate them (send new ObservationRequest for every existing path).

We don't plan to serialize org.eclipse.californium.core.observe.Observation, nor to use Java serialization, so the decision is up to you.

**Comment by sbernard31** [comment]
Ok so I finally decided to integrate the #649 PR in master even if `Observation` from californium is not `Serializable`.

This is not so costly,  it could maybe help someone and your usecase show it could make sense to create a store which serialize just registration without observation.
