### ISSUE TITLE
how will Leshan server do if lifetime in registration or reg update is 0?

### ISSUE THREAD

**Issue by mytruelove1986** [eclipse/leshan#688]
how will Leshan server do if lifetime in registration or reg update is 0?

**Comment by sbernard31** [comment]
The specification **§5.3 Client Registration Interface** says : 
>The LwM2M Client periodically performs an update of its registration information to the registered LwM2M Server(s) by performing the “Update” operation possibly without any parameters. If the lifetime of a registration expires without receiving an update from the LwM2M Client :
> - the LwM2M Server  MUST remove the registrationof that Client
> - the LwM2M Client MUST re-register (“Update” is not sufficient) to the LwM2M Server in order to be connected again, before initiating any further communication.

So this does not really make sense to have a lifetime to 0. (see https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/381)
More than that using a very small value for lifetime sounds not a good idea too ( see https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/283)

So back to the question... what Leshan server do ?

It depends of RegistratioStore you are using... because this is this class which is responsible to handle registration expiration.

If you look at `InMemoryRegistrationStore` and `RedisRegistrationStore` a cleaner task is launch each `cleanPeriod` and will remove expired registration. So With those stores the registration will expired(be removed) after a delay between 0 and `cleanPeriod` seconds.

Default value for `cleanPeriod` are 2s for `InMemoryRegistrationStore` and 60s for `RedisRegistrationStore`.

`RedisRegistrationStore` has also a `lifetimeGracePeriodInSec` (this is not really part of the LWM2M specification) which allow to extends lifetime returned by devices.

**Comment by sbernard31** [comment]
Could we close this issue ?
