### ISSUE TITLE
Bootstrap process with X509 certificate

### ISSUE THREAD

**Issue by raysad** [eclipse/leshan#690]
Hi,
I would like to know if the client private key is needed in the bootstrap process. Because, in the Bootstrap server Demo client private key is required. I looked at #638 and then in #626 you mentioned
>The Leshan bootstrap demo uses the Client certificate value to authenticate the client,
The Leshan bootstrap demo uses the Client certificate and Client private key values to write client credential for bootstrap server when client comes to bootstrap itself

So I am wondering is it possible to verify client certificate by the "trustedCertificates" during bootstrap without the need of client private key? Is Leshan bootstrap server able to modify client's LWM2M Bootstrap-Server Bootstrap information?
Thank you.

**Comment by sbernard31** [comment]
There are 2 main concepts about bootstrap server.

The `SecurityStore` which contains information about how a device should connect to server (using psk, rpk or x509 ). Here you don't need to know the private key.

And `ConfigStore` which contains configuration which should be written on device during bootstrap session. Here if you want to write the security object instance for bootstrap server and you are using x509 (without EST) , you need to write the private key and so you need the private key.

Leshan bootstrap server demo behaves a bit weirdly, because it uses data in `ConfigStore` as `securityStore`.

> So I am wondering is it possible to verify client certificate by the "trustedCertificates" during bootstrap without the need of client private key?

You should be able to verify client identity like this.

> Is Leshan bootstrap server able to modify client's LWM2M Bootstrap-Server Bootstrap information?

Yes, but you will not be able to write the security object instance for bootstrap server which is maybe not an issue for you.

**Comment by sbernard31** [comment]
Could we close this issue ?

**Comment by raysad** [comment]
Yes, thank you for your response.
