### ISSUE TITLE
The URLs of bootstrap server and lwm2m server are unmodifiable and fixed as one.

### ISSUE THREAD

**Issue by dnsgkr2** [eclipse/leshan#691]
I want to use bootstrap mode.  currently, in bootstrap webui BootstrapServerDemo can not set localAddress ip to 192.168.1.80 and LeshanLwm2mServer ip to 192.168.1.12

If you look at the attached picture ,if the bootstrap server and the lwm2m server are installed on different servers, the web ui  field LWM2M Server URL  value will not be changed.

When registering new bootstrap cofiguration in bootstrap web ui
ex) boostrap server  ip = 192.168.1.80
      lwm2m server ip = 192.168.1.12

![lwm2mip](https://user-images.githubusercontent.com/13491521/57433230-ea0bf080-7272-11e9-8c55-afa3a138e222.png)

![bootstrapip](https://user-images.githubusercontent.com/13491521/57433237-ed9f7780-7272-11e9-9ca2-70d63d4db036.png)

It does not matter if there is a bootstrap or lwm2m server on one physical server, but it seems to be a problem if it is located on another physical server. web ui can not be modified.
I am wondering whether the specification should be fixed with one uri or what is expressed in the web ui is a bug.

**Comment by sbernard31** [comment]
You are setting the bootstrap configuration for a given device.
The specification allows you write another bootstrap server than the one which is currently used for bootstrapping.
But our UI does not allow this. Why ? because we are using `configStore` as `securityStore` (like explained in https://github.com/eclipse/leshan/issues/690#issuecomment-490949978), but this is just a demo constraint...

**Comment by dnsgkr2** [comment]
Thanks for the answers to my questions.
