### ISSUE TITLE
Question on Send request with callback

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#756]
Hi ,

Leshan version : M10.

I want to understand how thread handling is done in send request with callback.

public <T extends LwM2mResponse> void send(final Registration destination, final DownlinkRequest<T> request,
            long timeout, ResponseCallback<T> responseCallback, ErrorCallback errorCallback) 

Till now I was using synchronous request to send a coap request to device but now my device is responding with almost 100 seconds of delay .  I do not want to wait the thread for so long and wants to respond on receiving the response. 

Any thread pool is maintained ? If maintained what are the configurations?

Thank you .

**Comment by madhushreegc** [comment]
Thank you very much for your response.

How does synchronous request works? send without call back?

**Comment by sbernard31** [comment]
Same thing except the current thread is blocked until the response is received or error is raised.

Look at [CoapSyncRequestObserver](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M12/leshan-core-cf/src/main/java/org/eclipse/leshan/core/californium/CoapSyncRequestObserver.java) to know how "sync" works and [CoapAsyncRequestObserver](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M12/leshan-core-cf/src/main/java/org/eclipse/leshan/core/californium/CoapAsyncRequestObserver.java) for async.

Method `onXXXXX()` from `AbstractRequestObserver` (Californium class) is called from a thread of californium protocol stage.

**Comment by sbernard31** [comment]
(should we close this issue?)

**Comment by madhushreegc** [comment]
Yes . Please close the issue.

**Comment by yemkay** [comment]
Just few follow-up questions:

1. When we invoke the async variant of send() method and if device ACK is delayed (due to it being in power saving mode), does it cause a thread to WAIT till the device ACK is received? 

2. If many such async send() requests to devices are waiting for ACKs and assuming no more thread is available in the protocol stage threads, what happens to a new request? Does send() become blocking till a thread is available? Or it gets added to a queue and send() is returned immediately? Or it gets discarded?

Thanks in advance!

**Comment by sbernard31** [comment]
1. no, the request is send then the thread is "free". (Thread does not wait for ACK)
2. If understand californium code correctly, there is a queue. If all thread are busy task will be queued and should return immediately. But again if you are using async send, thread should not be blocked.

**Comment by yemkay** [comment]
Sounds good!! Thanks for the clarification.
