### ISSUE TITLE
Race condition with observation on client update

### ISSUE THREAD

**Issue by vvalchev** [eclipse/leshan#77]
We have the following situation:
1. there is a client with endpoint 'endpoint' and registration ID "reg1".
2. we've provided an ObservationRegistryListener
3. we send observe request to a certain instance
4. simultaneously the client sends 'update' request to our server changing it's registration id to 'reg2'.

From that point, the ObservationListener.newValue() receives new values but the observation is with registration id 'reg1', while it should be 'reg2'.

Because of the invalid registration ID I'm also unable to find the client it is coming from. Therefore I suggest, that the Observation should contain the endpoint ID. Or, at least Leshan should update the existing Observations with the new registration ID, on ClientRegistryListener.updated(Client) event is received.

**Comment by sbernard31** [comment]
If I well understand, you say that an `UPDATE` change the registration ID ?
I think it's not allowed by the spec..

**Comment by vvalchev** [comment]
Hmm, good point! I should check the specification, and if you are right - then the problem is in the device I use. Thank you.

**Comment by p-koev** [comment]
I would just like to clarify, that this occurs when the device is restarted, not on update. It sends a new registration request with the same endpoint name and address, so it is assigned a new registration id. However the observation remains with the old registration id, and it notifies the ObservationListeners for value changes using that expired id.

**Comment by sbernard31** [comment]
Ok, this use case is no so clear in the spec. An [issue](https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/71) is open at the OMA
As I understand the spec, the observation lifetime is linked to a registration. 

When you said the registration remain you mean at client or server side ?
Which client implementation did you use ? Leshan client ?

**Comment by p-koev** [comment]
Real device connected to Leshan server. The problem arises because the observer request is triggered after the device goes offline, but before the lifetime interval has expired. So it is still present in the client registry. Then when the device quickly comes back online it receives a new registration Id, and also the observation request. Thus an observation is created both on the client and server, but the one in Leshan server still has the old registration Id.

**Comment by sbernard31** [comment]
When Leshan receive a new registration request, it cancels all observations of the previous registration.
An observation is linked to a registration so, it's normal that the old observation has the old registration id. But it should have a new observation linked to the new registration (if you resent the request)

Did you use Leshan server demo (previously named standalone) or did you use Leshan as a lib in your server ?
In this case, did you have custom implementation ? like a custom ClientRegistry for example ?

**Comment by p-koev** [comment]
We're using leshan as a lib in out application. With the default client registry. And the observation request isn't being resent by us, but one the coap implementation (ReliabilityLayer). But it has been queue before the client re-registers, so it contains the old registration id.

**Comment by sbernard31** [comment]
Ok I understand.
This looks like a bug. I don't see an easy fix right now...
Some ideas:
 1. Reuse the same RegistrationID, if a client is already register. (This should work, but the behavior should be a bit strange. I mean, I send a request from a registration and I accept the response after another one, I'm not sure to see all the impacts).
 1. When we receive the response check if the registrationID use to send the request is the same than the current one. If not ignore the response and cancel the request.
 1. Cancel all pending requests on deregistration/reregistration.

**Comment by sbernard31** [comment]
@p-koev  Does it behave better since we cancel pending request on de-registration ?

**Comment by sbernard31** [comment]
Now, we merge the ClientRegistry and observationRegistry in RegistrationStore (#210) remove observation et registration in an atomic way.

We also try to cancel pending request on de-registration. (#100)(which should limit the retransmission)

We also add the registrationID in the context of the observe request to know which registration is targeted. ( #174)

All of this should fix this bug.

@p-koev @vvalchev  I really appreciate if you could confirm that this issue is fixed now.
If this is not the case please re-open this issue.
