### ISSUE TITLE
Client tries to connect with initial PSK credentials after bootstrapping second time

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/leshan#80]
Below was the steps followed with leshan-0.1.11-M8 snapshot.

1. Bootstrap server(BS), Leshan Server(DM) and client started. Client successfully bootstraps and connects to DM server
2. Change PSK credentials: In both Bootstrap & DM server, I changed PSK credentials for the client(matching credentials in both DM and BS). I kept the DM server ip and port unchanged. Now Client's _UpdateRequest_ fails, followed by Client _RegisterRequest_ fails. Client now goes to BS and is successfully bootstrapped with new credentials.
3. Issue: Client now tries to connect to DM server, but with the original credentials. It fails.

Attaching [logs](https://github.com/eclipse/leshan/files/138973/bs.txt) with commands used to invoke all three. I am using unchanged code as from leshan-0.1.11-M8 snapshot

**Comment by sbernard31** [comment]
As the server has the same IP/port, the client continue to use the same DTLS connection.
There is no new handshake with the new credentials.
This is clearly a bug.

**Comment by sophokles73** [comment]
@sbernard31 what you say is true if the client has been up and running all the time, i.e. has not been restarted in between. The client will need to evoke its connection to the DM server from Scandium's  `ConnectionStore` after having been re-provisioned with new credentials. I don't think that we currently expose any API that would make this possible, do we?

**Comment by sbernard31** [comment]
I don't look at this deeply, but I think you're right  there is no API to do that for now.
I wonder if we should close the connection at server side too ?

**Comment by sophokles73** [comment]
I think that would make sense in order to prevent continued usage of the established connection with now expired credentials. The reason for changing the credentials might have been to shut out/prevent a potential attack in the first place, right?

This discussion brings me back to what I have thought about some time ago regarding the introduction of a generic security API in Scandium for managing the interaction between Scandium's handshakers and the (user provided) security/credential stores.

**Comment by sbernard31** [comment]
At short term we should consider to use `DTLSConnector.close()` at client side, after a bootstrap.

**Comment by sbernard31** [comment]
I finally use the `ConnectionStore.clear()` waiting we are a better way to do that in californium/scandium.

**Comment by sbernard31** [comment]
This is fixed in master (commit 8066e9b)

**Comment by lhotari** [comment]
FYI @sbernard31 , It looks like [the changes to fix this issue are now gone in latest master branch](https://github.com/eclipse/leshan/commit/ad6fe623b3ec0f13bbb152f9e42ccbea2097ac0f#diff-96e796028695a74ba7a60ca9273baa23L98). 

However I'm happy with the removal of the previous solution since that was causing a situation where the bootstrapping doesn't finish successfully from the bootstrap server's perspective since the response to the finish request in bootstrapping wouldn't get delivered when using DTLS. It doesn't fail every time since there seems to be a race condition. 
Sometimes the response is sent before the DTLS sessions have been cleared and it succeeds, sometimes it fails and logs something like "DTLSConnector (DTLS-0.0.0.0/0.0.0.0:43076) drops 12 bytes to localhost/127.0.0.1:5684" since the DTLS session where the request arrived has been removed.
The previous solution most likely also has a race condition with the connection to the LwM2M management server.

**Comment by sbernard31** [comment]
@lhotari I'm a bit confused. Are you described an issue which is fixed now in master or are you pointed there is a new issue in master ?

**Comment by lhotari** [comment]
@sbernard31 I'm referring to this change, committed originally 11 Dec 2017 and merged to master on Aug 16, 2018 : https://github.com/eclipse/leshan/commit/ad6fe623b3ec0f13bbb152f9e42ccbea2097ac0f#diff-96e796028695a74ba7a60ca9273baa23L98 . It removed the fix for this issue #80. 
These are some of the lines that were removed:
```
            if (securedEndpoint.getConnector() instanceof DTLSConnector) {
                final DTLSConnector dtlsConnector = (DTLSConnector) securedEndpoint.getConnector();
                observers.addObserver(new LwM2mClientObserverAdapter() {
                    @Override
                    public void onBootstrapSuccess(ServerInfo bsserver) {
                        dtlsConnector.clearConnectionState();
                    }

                    @Override
                    public void onBootstrapTimeout(ServerInfo bsserver) {
                        dtlsConnector.clearConnectionState();
                    }

                    @Override
                    public void onRegistrationTimeout(DmServerInfo server) {
                        dtlsConnector.clearConnectionState();
                    }

                    @Override
                    public void onUpdateTimeout(DmServerInfo server) {
                        dtlsConnector.clearConnectionState();
                    }
                });
            }
```
I'm not asking to return these lines since that solution already had an issue (race condition in finish response) I was trying to describe in my previous comment.

**Comment by sbernard31** [comment]
ad6fe62 removes the line of code related to this "fix", because with the refactoring this line are not needed anymore as a fresh new endpoint/connector is recreated each time we bootstrap.

So there is no risk we reintroduce this kind of code in master.

But, I still does not understand if the current state of master contains the same kind of issue or race condition you described above?

**Comment by lhotari** [comment]
@sbernard31 Thanks for explaining. Great that it's all ok. I didn't fully understand the refactored solution and my concern was that some features were dropped in the refactoring. I didn't test with latest master and I made the conclusion by reading the code. I'm sorry for the noise I caused with these comments.
