### ISSUE TITLE
Unable to "talk" to long sleeping devices behind NAT (patch)

### ISSUE THREAD

**Issue by sdrsdr** [eclipse/leshan#852]
For a NB-IoT devices we're facing NAT inflicted communications problems:
As lwm2m protocol us  UDP based and our devices usually sit in mobile operators private networks we can't always assume working communication path from server to device. To be able to talk to our device we always observer our device on registration and have command queues for every device holding commands to that device to be executed when a periodic "refresh" of the observation is triggered by the device and the NAT channel is granted (usually for just 30 seconds). When the NAT session expires the next UDP packet from the device is with different port and probably different host. With default Network config this breaks the registration matching but luckily this can be overcome with some `coapConfig.setString(NetworkConfig.Keys.RESPONSE_MATCHING,"PRINCIPAL");` and timeout tweaking. Yet  in the current code the registration identity is immutable and never changes  but this does not reflect the reality in our scenario and when the NAT session is recreated you should "talk" to the identity of the coap responce and not to the original registration identity. I've managed to device a minimal change to the current code base that allow proper communication in our scenario. The commit that does the trick is here:

https://github.com/sdrsdr/leshan/commit/6d569616e52c9d151eaddef4199fbf8922fa7d23

If there is a interest in this patch I can do a proper PR :)

**Comment by sbernard31** [comment]
LWM2M behind a NAT is a bit tricky.

The way we make it works : 
1. Using LWM2M Queue Mode.
2. When LWM2M client wakes up 
2.1.At DTLS level : do a new handshake or abbreviated one (as IP/port changed so DTLS connection can not be retrieved)  or use [connection id](https://tools.ietf.org/html/rfc6347) (to identify connection by Id instead of IP/port).
2.2  At LWM2M level, client should start communication by doing an update (this will update the ip address of the registration). This seems to be mandatory. (see https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/391)
3. When LWM2M server receives an update, we send pending request sequentially.

So If you want to strictly respect the standard, I advice you to try to do something like this.
Could it be possible for you or do you see some blockers here ?

**Comment by sdrsdr** [comment]
We don't use DTLS. NB-IoT have ridiculous  restrictions on number of packets send/received per hour too, so to keep user experience at somewhat satisfactory level we must make sure any packet we send is data packet and not "maintenance" one. On the other hand we use specific hardware with vendor provided LwM2M stack  that is far from feature complete ..

**Comment by sdrsdr** [comment]
This solution is working and solves real issue for us and probably for others. It can be made optional via a network config. I don't see how it can introduce any problems to the stack itself, the "code" is just few lines, does not involve loops or any complex data structure manipulations so it should have no noticeable performance impact. IMHO it will just make the already great code even more versatile :)

**Comment by sbernard31** [comment]
> We don't use DTLS

Uups I didn't understand that. `PRINCIPAL` response matching mode is more about DTLS. If you don't use DTLS maybe semantically this is more correct to use `RELAXED` mode. In practice, this would be the same for `coap://`  (see [EndpointContextMatcherFactory](https://github.com/eclipse/californium/blob/2.2.3/californium-core/src/main/java/org/eclipse/californium/core/network/EndpointContextMatcherFactory.java#L49)) 

> NB-IoT have ridiculous restrictions on number of packets send/received per hour too, so to keep user experience at somewhat satisfactory level we must make sure any packet we send is data packet and not "maintenance" one

I suppose you meant that you don't want/be able to start your communication with an UPDATE request. I encourage you to double check if this is really impossible to you as this is really out of spec.

> This solution is working and solves real issue for us and probably for others.

I looked at your code and the main issue is that `Registration` must be immutable because `RegistrationStore` could be shared/persistent. And so just change the attribute value will not apply the change in the shared store.

So, if I understand, your need is to be able to update registration on notification. I think a proper way would rather be to update registration on notification like this : https://github.com/eclipse/leshan/issues/544#issuecomment-407400523

Could it works for you ?




I looked at you code

**Comment by sbernard31** [comment]
I think a bit more about the proposition I proposed above and there is some issue : 
 - other observation listener will not have the registration updated
 - this doesn't really works with PresenceService.

Are you using `PresenceService` ?

**Comment by sbernard31** [comment]
You could also have a look to this  #854 PR I just created.

**Comment by sdrsdr** [comment]
This PR is way above my understanding of inner workings of leshan/californium but seems to "export" all the right interfaces. I'm looking forward for testing it once it got to master. The approach in the comment pointed above should also work bit if the PR goes in master we won't need that "hackish"  implementation :) Thanks alot!

**Comment by sbernard31** [comment]
Any chance that you can test #854 before I integrate it in master ?
This PR is pretty much dedicated to you so I would prefer to be sure it works for you before to integrate it.

**Comment by sdrsdr** [comment]
No problem I'll be honored to test the PR.. It just might take some time ..

**Comment by sdrsdr** [comment]
I can confirm that the PR works in our case! Thanks!

**Comment by sbernard31** [comment]
The #854 is now integrated in master and I add some documentation in the [wiki](https://github.com/eclipse/leshan/wiki/LWM2M-Devices-with-Dynamic-IP).

**Comment by sdrsdr** [comment]
Great work! Thanks again!

**Comment by sbernard31** [comment]
@sdrsdr, if you can maybe you could add Allterco as Leshan adopters ? https://github.com/eclipse/leshan/issues/830
