### ISSUE TITLE
Deregistration/Registration in less time, a command from device is lost

### ISSUE THREAD

**Issue by developez** [eclipse/leshan#871]
I am using leshan server. My devices are registered without problem to the server, then, i observe the endpoint 19/0/0 and then I receive the commands send by the devices, the problem is that in less time when the device sends again a command a registration action happens, then the device make the registration again and that previous command is lost.

In summary, this is the situation.

![tinyaaa](https://user-images.githubusercontent.com/1931408/89181117-5a4b1400-d593-11ea-9bca-9afffe51aa4d.PNG)

**Comment by developez** [comment]
> I am using leshan server. My devices are registered without problem to the server, then, i observe the endpoint 19/0/0 and then I receive the commands send by the devices, the problem is that in less time when the device sends again a command a registration action happens, then the device make the registration again and that previous command is lost.
> 
> In summary, this is the situation.
> 
> https://i.ibb.co/PrcYgPY/tinyaaa.png

**Comment by developez** [comment]
Reopen, sorry, it was a mistake.

**Comment by sbernard31** [comment]
Hi, 
Your issue is not really clear to me, when you say "registration timeout", you mean that "the registration at server side expired" ?
The registration lifetime is send by the device on register request. (`lt` query option) The value should be in seconds.
After this time without any successful registration update, the registration expired. 

By the way which kind of command is send by the device ? in LWM2M 1.0.x the only uplink request are "register"/"update"/"deregister". So I'm not sure to get what is "COMMAND XYZ" (maybe notification from 19/0/0).

Also there is a `Deregistration` message from server to the device, don't get what this is too?

**Comment by sbernard31** [comment]
I guess you finally found a way : https://github.com/eclipse/leshan/issues/872#issuecomment-671847421

(If I'm wrong to not hesitate to reopen)
