### ISSUE TITLE
Ignore notify by CON GET from device

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/leshan#887]
Hi ,

Leshan version : 1.0.1

As of now , leshan server send RST message to device on receiving notify from device when observe on resource is not created .
Is there any way so that notify message is ignored and no response is sent back to device?

Regards,
Madhushree.

**Comment by sbernard31** [comment]
This is more a CoAP/Californium question.

AFAIK, there is no way to do that.

Which makes sense as this is how this is specify in the rfc : 
```
   If a client does not recognize the token in a confirmable
   notification, it MUST NOT acknowledge the message and SHOULD reject
   it with a Reset message; otherwise, the client MUST acknowledge the
   message as usual.  In the case of a non-confirmable notification,
   rejecting the message with a Reset message is OPTIONAL.
```
(source : https://tools.ietf.org/html/rfc7641#section-3.5)

**Comment by madhushreegc** [comment]
ok . Thank you .

**Comment by boaks** [comment]
@madhushreegc 

Check issue #864 

The only way to solve that, is to use a proper client!
As long as you don't provide the information, which client you are using, as long that issue will not be solved.

**Comment by madhushreegc** [comment]
Ok . I was using Anjay client . 

Thank you for clarification .

**Comment by boaks** [comment]
Usually the scenario is to tell the lwm2m-client (coap-server, which sends notifies on changed data), that the lwm2m-server (coap-client, which sent the observe request), is not longer able to process the notifies and so your lwm2m-client may stop to send such "unusable notifies" in order to save bandwidth and energy.

So, what is your scenario, why do you want the RST to be not sent?

**Comment by madhushreegc** [comment]
Yes,the case is , If  lwm2m server(coap-client) does not respond back , device can start registration process.

**Comment by boaks** [comment]
Hm, usually, if the device sends NON notifies, it doesn't get any message back.
So, how does your client then distinguish between a NON notify (successfully processed) and a NON notify (not processed) in order to start the registration? My feeling is, it either starts registrations very often or not. But I'm not sure, if suppressing the RST will help you. If I find time in the next day, I add a Californium.NetworkConfig to suppress RST for NONs. But I'm really skeptical, that this helps you out.

**Comment by madhushreegc** [comment]
Actually device is sending CON notifies . So as per spec , acknowledgement is must .  

This is something need to be fixed at device side .

Thank you so much for your support ..

**Comment by madhushreegc** [comment]
@boaks

Hi,

Sorry to re-open again . Other than log , is there any way, some class method can be notified for failed notifies?  If so , we can send the observe request on the failed notifies towards device?

**Comment by boaks** [comment]
The question will be, which of the peers should be notified. The "notify-responses" are sent by the coap-server (lwm2m-device). If CON is used, the coap-server may get either a ACK, a RST, or a timeout. A Californium's `MessageObserver` will be called on those events.
But I'm not sure, what "failed notifies" should cause on the coap-client (LwM2M server)?

**Comment by madhushreegc** [comment]
For the CON notify on non-observed resource , RST is sent back to the lwm2m device .  

Use case is like, some how I have to parse the payload and trigger the observe request on the device for that path(fetched from the notify payload) .

**Comment by boaks** [comment]
I'm not sure, if I get it:

if the coap-client (lwm2m-server) receives a notify, the server can't process, it sends a RST to the coap-server (lwm2m-device) in order to stop that device from sending notifies, the server is not able to process. 
To overcome that, the lwm2m-server must send an observer-request again, but that requires an trigger.
Before that notify-rejection happens, somehow the lwm2m-server must  have lost the request! I'm not sure, if you use the clustered-observe-client or a simple one. And I don't know, if leshan offers a callback to indicate, that such a observer-request get "canceled" (or lost somehow else). I also don't know the root-cause of such a lost observer-request. Maybe, investigating for that helps to find a solution.

**Comment by madhushreegc** [comment]
Yes , I will check all the logs for the root cause .

Thank you so much for the valuable input.
