### ISSUE TITLE
Which minimal version of java for Leshan 2.0.0 ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/leshan#924]
Leshan 1.x is compatible with java7.
Main reason of that was to [support (or at least try to support) android](https://github.com/eclipse/leshan/wiki/F.A.Q.#can-i-use-leshan-with-android-).

With the development of the new version 2.0.0, the question is: 
**Should we still target java7 or a more recent version of java ?**

Californium project wonders the same thing.(https://github.com/eclipse/californium/issues/1159#issuecomment-722918877)

Feedback from community would be strongly appreciated. :pray:

**Comment by sbernard31** [comment]
Regarding https://github.com/eclipse/californium/issues/1159#issuecomment-724612491, we currently go to java8 as minimal version.

**Comment by sbernard31** [comment]
Moving to java 8 could allow to use JLine 3 (#1065) waiting JLine2 seems to doing well. (#1064)

**Comment by sbernard31** [comment]
Logback 1.3.0 which could be need for #568 need [java8 at runtime](http://mailman.qos.ch/pipermail/announce/2021/000156.html).

**Comment by Michal-Wadowski** [comment]
In the https://github.com/eclipse/leshan/wiki/F.A.Q.#can-i-use-leshan-with-android- links "leshan-android-demo" and "LwM2MDemoClientAndroid" are not working. It seems to no one actively support android with leshan.

**Comment by sbernard31** [comment]
> In the https://github.com/eclipse/leshan/wiki/F.A.Q.#can-i-use-leshan-with-android- links "leshan-android-demo" and "LwM2MDemoClientAndroid" are not working. 

I fixed links (it seems those projects are still available on github but through some other links :grimacing:)

> It seems to no one actively support android with leshan.

As said, in F.A.Q. : Developers team never tested Leshan with android at least AFAIK.
There is not official support of it but I think it makes sense to not close the door to android if this is not too costly.

**Comment by sbernard31** [comment]
Java 8 will be supported for a long time (2026/2030) :  
 - [Adopt OpenJDK Release Roadmap](https://adoptopenjdk.net/support.html#roadmap)
 - [Oracle Java SE Product Releases](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)

For Android this is not crystal clear but I guess java 8 should be OK.
See:  https://stackoverflow.com/questions/69643374/which-java-version-should-i-use-to-create-a-library-usable-with-android)

During development and only if new API is needed, we could also change the API level to target to a more recent version of android.
See: 
 - https://www.appbrain.com/stats/top-android-sdk-versions
 - https://apilevels.com/

**Comment by sbernard31** [comment]
So since #1159 is integrated we are building with java8.

**Comment by Michal-Wadowski** [comment]
No we can use syntax sugar from java8 :smile: I'm very glad for this :grin:.

**Comment by sbernard31** [comment]
For syntax sugar, I guess yes but about the java 8 API, you could be limited by the Android level API set. :)

Coding a reusable library is like living in the past :grimacing:

**Comment by Michal-Wadowski** [comment]
But I don't see any mechanism preventing us to use java8. How we ensure that we don't break android API?

**Comment by sbernard31** [comment]
This should be done by `animal-sniffer-maven-plugin` : see https://stackoverflow.com/questions/11048805/maven-plugin-for-checking-api-compliance-with-android/49153640#49153640

**Comment by minusdavid** [comment]
Going forward, is there anywhere that we can easily find the minimal version of Java within the codebase?

I noticed on https://ci.eclipse.org/leshan/job/leshan/ that Java8 is still being used, so I'll use Java8.

The README.md would benefit from either a reference to Java8 or a reference to a place to check for the required Java version. 

(The required mvn version would be good too actually.)

Thanks!

**Comment by minusdavid** [comment]
Oops actually I'm using the 1.4.2 jars from https://search.maven.org/search?q=g:org.eclipse.leshan%20AND%20v:1.4.2%20AND%20!a:leshan to set up some local demos.

So based off https://ci.eclipse.org/leshan/job/leshan-1.x/ I'm guessing that I should actually be using Java 7?

**Comment by minusdavid** [comment]
Although Java 7 appears to be EOL. 

Looks like things are in a bit of a purgatory between Leshan 1.4.2 and 2.0.0...

**Comment by sbernard31** [comment]
> Going forward, is there anywhere that we can easily find the minimal version of Java within the codebase?

**OK I will add this in the README.**

But I don't understand why you search on Jenkins to know the minimal version, if you find this issue #924.
If you read this thread,  it"s is clearly said that : 
 -  Minimal Java version is Java 7 for Leshan 1.x
 -  Minimal Java version is Java 8 for Leshan 2.x
 
 Note this is not the required Java version but the minimal one.
As Java is mainly backward compatible, you can use more recent version of java (and of course you should)
Targeting  a very low version of java is just a way to make the library usable by as many people as possible.

>  The required mvn version would be good too actually.

For this one, I'm not so sure, the Leshan maven build should tell you if you are using a too old version of mvn.
And if you know maven, it's pretty easy to see the minimal maven version : 
https://github.com/eclipse/leshan/blob/a314ff2fc0a927c41176eeb81df72fcab7d23ec7/pom.xml#L476-L483 

By the way no need to be a maven expert to check java minimal version too : 
https://github.com/eclipse/leshan/blob/a314ff2fc0a927c41176eeb81df72fcab7d23ec7/build-config/pom.xml#L39-L46

> Oops actually I'm using the 1.4.2 jars from https://search.maven.org/search?q=g:org.eclipse.leshan%20AND%20v:1.4.2%20AND%20!a:leshan to set up some local demos.
> So based off https://ci.eclipse.org/leshan/job/leshan-1.x/ I'm guessing that I should actually be using Java 7?

No you can just use the Java version of your choice, I must confess that I'm a bit confuse if you want to create demo based on Leshan, just create your maven project using any JDK you want and add Leshan as dependency... 
It seems to me that you try to build Leshan locally and I don't understand why ...

> Although Java 7 appears to be EOL.

And so what ? When Leshan 1.x was out (mid-2020) Java 7 was still maintained.
Java 7 end of life was July 2022.

We will not change minimal java version for minor version ...
And again we don't force you to use java 7 just make it compatible for it ...

> Looks like things are in a bit of a purgatory between Leshan 1.4.2 and 2.0.0...

Could you elaborate what is the point here ?

**Comment by minusdavid** [comment]
@sbernard31 : Thanks for adding that information to the README. 

The first comment said "Leshan 1.x is compatible with java7" but it didn't say anything else and the rest of the thread was about Leshan 2.x. That first comment was also 2 years old, so I wasn't sure if it still applied.

I use a few other projects that can't support newer versions  of Java, so based on the wording I thought it might not be able to use newer versions of Java. 

I've had similar problems with Maven versions in the past too, although that was quite a few years ago now.

You can probably guess that I don't use Java often.

--

I'm not very familiar with pom files and Maven plugins, but I did see that leshan/build-config/pom.xml, but only in the master branch. It didn't exist in the 1.x branch. I looked at https://github.com/eclipse/leshan/blob/1.x/pom.xml but I didn't really understand how the different references to 1.7 and 1.8 applied. 

--

At https://github.com/eclipse/leshan#compile-leshan--run-demos you have the following line: "mvn clean install"

At the moment, I'm just downloading the already compiled JARs, but I thought it might be interesting to tweak the demo and compile it, so that's why I was wondering about the Maven version. 

I figured at this point it made more sense than to use trial and error.

--

As for my comments about Java 7 being EOL and "purgatory", that was just a misunderstanding on my part. Your other comments have clarified everything and helped me to understand. 

No worries at all.

**Comment by minusdavid** [comment]
I'm used to projects like Keycloak that usually tell you which Java version to use in the Getting Started (e.g. https://www.keycloak.org/getting-started/getting-started-zip)

So I appreciate the update to the README. 

And I appreciate the Leshan project! Thanks to you folk and Sierra Wireless in general. 

I work on an IoT project that pre-dates the LwM2M protocol, but we're getting some new components with embedded LwM2M clients, so looking to test out that client functionality, and the Leshan client demo and Leshan server demo have been really helpful for testing that hardware.

I'm still thinking about how we'll use Leshan in production. I figure we'll probably wrap it with an API interface that lets us integrate it into existing user consoles, especially since we'll only be using a very small set of LwM2M functionality. 

I'll probably have more questions in the future, so merci beaucoup d'avance!
