### ISSUE TITLE
Leshan connectivity/queue mode?

### ISSUE THREAD

**Issue by UnforgivenD** [eclipse/leshan#948]
Hi, we are trying to setup Leshan 1.0.0 with real device based on wakaama client.
and it seems that there is strange behaviour - after client connects, we have very short amount of time (up to 10 seconds) when 
read or write can be done and received by client.  If read/write will be done afterwards - server will get timeout. 
But if client will send notification on observed resource - server will immediately push all read/writes to client, like them was in queue. 
Maybe you can help with that.

Thanks in advance!

**Comment by sbernard31** [comment]
When using queue mode, Leshan use `PresenceService` to estimate if client is present or not. 
By default we consider the device is present since last communication to 93s after (CoAP default MAX_TRANSMIT_WAIT) as defined in LWM2M specification.
By the way when Leshan consider the device absent it raises a `ClientSleepingException`

So if the time you observe is more around 10s, I guess this is maybe not a Leshan issue but something else like maybe very short NAT expiration. (10s sounds really short, I have already heard about 30s but not 10s :thinking:)

> But if client will send notification on observed resource - server will immediately push all read/writes to client, like them was in queue.

As UDP is not reliable layer (packet can be lost), CoAP uses Acknowlegde+retransmission to ensure message is received.
In your case **maybe**, NAT expires (or any other reason) so first request sending is not received. This generates some retransmissions and when your device talk again (e.g. it reopen NAT route) device finally received one of this retransmissions. 
(you should read CoAP RFC for more details about this)

But there is no queue implemented in Leshan. 

**Again I really advice you to look what happens at network level using wireshark.**
This could help a lot to better understand the situation.

**Comment by FengchenShen** [comment]
After the client connects with the server, we can read/write object resources one by one. But if we do nothing when the client connects, and perform read action after about 90s, the client can not recieve the command from server. 
Does this problem relate to MAX_TRANSMIT_WAIT ？ And how to resolve this issue ?
> By default we consider the device is present since last communication to 93s after (CoAP default MAX_TRANSMIT_WAIT) as defined in LWM2M specification.

**Comment by sbernard31** [comment]
Does your client register using QueueMode ? 
Are you in a NAT environment ? 

I repeat my self again an again but a wireshark capture could help.

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by UnforgivenD** [comment]
yes, thanks, issue was resolved, closing it!
