### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by matthvi4l** [eclipse/leshan#962]
Is it possible to run leshan in a multi-tenant setup ? Do you have any recommendations with the current code ? What would be the required changes to improve multi-tenant support ?

A far as I know, there are currently few problems:
- the object model registry is shared for all lwm2m clients of the same leshan server instance. 
- it's possible to find a registration by endpoint name with the registration store API. so we can't have the same endpoint name in 2 different tenants.
- TLS and OSCORE also use the endpoint name to identify the device. So duplicate names is again a problem.

**Comment by sbernard31** [comment]
I'm not sure what you have in mind with a "multi-tenant-setup". My first idea will be to have 1 Leshan Server by tenant but I suppose if you ask this question, it's because this is not OK for you and you want to keep some part of Leshan in common ? :thinking: 

Maybe you could detail a little more the design you have in mind or your needs.

I will try to answer to your point anyway (but as I don't get the big picture, his could be not so relevant).

> the object model registry is shared for all lwm2m clients of the same leshan server instance.

You mean `LwM2mModelRepository` ? The repository contains all the models (in different versions).
So this should be OK, except for private range ID... I mean If 2 tenants want to use 2 private ID for 2 different objects.
But `LwM2mModelProvider` is not dependent to `LwM2mModelRepository` and so you can imagine that model provider could have a repository per tenant.
Another solution would be to add a way to request model by tenant ID but before to do that we need to see if the big picture make sense. 

> it's possible to find a registration by endpoint name with the registration store API. so we can't have the same endpoint name in 2 different tenants.

Correct. LWM2M specification is pretty clear an endpoint name should be unique : 
_"The Endpoint Client Name identifier MUST be unique at the server or servers it is being used with."_ 
There is even some recommendation to define a unique endpoint name (see http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#Table-731-1-Endpoint-Client-Name)

> TLS and OSCORE also use the endpoint name to identify the device. So duplicate names is again a problem.

About OSCORE is not clear enough to me for now, so no comment. 
About TLS, there is at least an issue for PSK identity which should be unique too and probably also for X509 as CommonName should be equals to endpoint name.

**Comment by matthvi4l** [comment]
There are multiple ways to do it and the most obvious is a cluster (for HA) of server instances per tenant and probably a mapping DNS name - server port.

Now if we want to reuse the same server we need to find a way to segregate the lwm2m clients on the server. It could be a endpoint name prefix per tenant. Or we could enforce unique identifiers (eg MSISDN) in endpoint name and have an additional tenant store to gather endpoint names in tenants. It should be possible to implement a new LwM2mModelProvider that uses this new store to provide a model per tenant or per endpoint. So it seems we're OK here too. And if we use a unique endpoint name, we should be good with TLS and OSCORE.

**Comment by sbernard31** [comment]
Does it mean you finally think you should be able to use Leshan in a multi tenant way for your use case ? 

Please do not hesitate to use this issue to share with us more about your experiences about how using Leshan in a multi tenant way. Maybe we could also create a wiki page about this.

> And if we use a unique endpoint name, we should be good with TLS and OSCORE.

I'm not sure to get why ?

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by sbernard31** [comment]
I close it but feel free to reopen or comment if needed.
