### ISSUE TITLE
Unable to start observation on resource

### ISSUE THREAD

**Issue by threekami** [eclipse/leshan#969]
500 Invalid Response:Unable to decode response payload of request [ObserveRequest [path=/32000/0/4 format=ContentFormat [name=TLV, code=11542]]] from client [Power_Tool]

32000.xml has been set to opaque type.

+QLAURC: "observe",64435,0,32000,0,4
AT+QLAOBSRSP=64435,1,32000,0,4,2,16,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,0
ERROR

**Comment by sbernard31** [comment]
Please precise which version of leshan you are using.
I guess you are using Leshan at server side and your own device at client side ? 

You probably have a more detailed description of the error in logs. Please provide it.
A [wireshark capture](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing) could help to see exactly what is sent by the device and so evaluate if this is a problem at client or server side.

The AT commands logs doesn't really help, if you don't give what means each value.
>  AT+QLAOBSRSP=64435,1,32000,0,4,2,16,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,0
64435 = MID ?  
1 = Token ? 
32000,0,4 = path ? 
2 = ? 
16 = ? 
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = payload ? 
0 = content format ? 

I don't know... please provide IP capture instead of unusable logs.

**Comment by sbernard31** [comment]
should we close this issue ?

**Comment by threekami** [comment]
yes, cheers



发自我的iPhone


------------------ Original ------------------
