### ISSUE TITLE
if i can restore the observation when restart the device

### ISSUE THREAD

**Issue by weicanqd** [eclipse/leshan#975]
dear leshan team：
I have an issue that i need restore the observation for a resource path when restart the device. 
i check the code and find the observation will been destoried when the lwm2m client shutdown.

i see the InMemoryObservationStore class, but it seems that the start function desn't create the new observe. only debug the log.

i think i need to establish an observeRelation when the client restart by the old token. also i can backup the before observe token.
but i don't know when and where to create new observeRealtion,  
in coapEndpoind start time? 
please hlep me, thank you !

**Comment by sbernard31** [comment]
I'm not sure if you are talking about Leshan at client or server side ? :thinking: 

You want to restart a Leshan client without losing  observe relation ? 
OR
You want to restart a LWM2M client and want the leshan server reestablished the observe relation ?

**Comment by weicanqd** [comment]
> I'm not sure if you are talking about Leshan at client or server side ? 

I'm talking about the Leshan client side.

> You want to restart a Leshan client without losing observe relation ?
> OR
>  You want to restart a LWM2M client and want the leshan server reestablished the observe relation ?
 
 I want to restart a leshan client and reestablish the losing observe relation.

**Comment by weicanqd** [comment]
hello sbernard31
my point is that from VZW requirement as below
**In order to avoid network traffic increase, the LwM2M Client SHALL maintain previous observation states in case of reboot, power cycle, etc**

**Comment by sbernard31** [comment]
Ok I get it now. 

We do not have dedicated code about this in Leshan.
This sounds more like a CoAP feature so probably a californium question.  (even is the recommendation is about LWM2M)

Personally, I didn't play too much with the `ObserveRelation` at CoAP server side (LWM2M client side) and I have no idea if this is doable easily. 
But maybe @boaks could have any idea about this ? 

@boaks  when there are questions related to californium reported to Leshan : 
 - do you prefer I "ping" you in the Leshan issue
 - OR  I create(or ask to create) a new issue in californium (with a link to the Leshan one)

**Comment by boaks** [comment]
> @boaks when there are questions related to californium reported to Leshan :

Usually, I try to read the leshan issues. Sometimes with delay. 
At least, if you ping me here, then I try to answer. 
So, no general need to create a Californium issue. 

About the feature:
I think it is implementable, maybe not too easy, but also not too hard.
The question is more, who is willing to spend time into that feature.
For me this is not that important, at least I don't plan to use it.

@weicanqd 

Do you know any (coap) implementation, which is able to do that?
For me this seems to be a device-client feature and so I would expect, to find that there.
Wakaama doesn't do it, right?

**Comment by boaks** [comment]
Let me add:

@weicanqd 

Do you use the leshan (demo) client for testing and demonstrating?
Or do you use for other scenarios (closer to production)?

**Comment by weicanqd** [comment]
hi boaks
I use the leshan client to test for VZW lwm2m feature. 

if you don't plan to do this feature. can you give me some suggestion for do that？

I use the californium-core and scandium-core source code for leshan lwm2m client，also  i take sometime to read the source code for coap exchange ,request and options.  
if i restore an observe relation when client restart again,  should i need to backup the exchange info for previous observe and invoke function:
 new ObserveRelation(remote, resource, exchange);
if i do this, client will check the current observeRelation and handle observe request when invoke setfireResourcesChange(resource id).

**Comment by boaks** [comment]
Not all classes and there instances are intended/designed to be serialized and deserialized.
So such an extension may require some code changes in Californium.

(For scandium my latest development is to offer a graceful-restart, so the dtls-state could be saved and loaded (but requires the upcoming version 3.0.0-M1.) )

The server part of the observes is implemented in `californium-core`.
The state is split around.

- `CoapResource.observeRelations`,
- `ObserveRelation`
- `ObservingEndpoint`
- `ObserveManager`
- `ObserveRelationContainer`

For the `ObserveRelation` it's required to serialize
- `Exchange` (including the `Request`

Especially for observed servers, it may also be important to store the last used MID for outgoing notifies in order to prevent a too early reuse of such a MID.
 
I guess, it will take a small couple of weeks (1-3) to implement that. So, if you think it pays off, you may check these classes to start with.

**Comment by weicanqd** [comment]
HI boaks,
Thanks a lot for your suggestion.
We should move the discussion and questions into Californium.
thank you!

**Comment by boaks** [comment]
Hi @weicanqd 

> I use the leshan client to test for VZW lwm2m feature.

Let me mention again:

If a lwm2m-device-client is able to save and restore it's coap-observe-server state is mainly a question of the used coap-library. That's the nasty thing, if you use a function, which based on artifacts "within" the stack (RFC7252/RFC7641). Even, if you add that to Californium, this doesn't demonstrate anything for other coap-stacks. I have my doubts, that this feature is "widely" implemented. Therefore I recommend to check other implementations before you start to spend your time in.  

Long ago, we tried to discus that [OMA - LwM2M - Alternative approach for RFC7641](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/171). An alternative, which is not based on stack internal artifacts but on application level data, it would be much easier and also more "portable" among coap-implementations. The basic idea was that you add a "reporting" flag to the resource, and the lwm2m-device then sends requests, e.g. "put coap://..../notify/5/0 <payload>" in order to notify the server of a change. Beside of "incompatibility to coap-proxies", that would come with a slightly performance penalty, but with much more possibiilites and "portability".

**Comment by boaks** [comment]
> We should move the discussion and questions into Californium.

You're welcome.

**Comment by sbernard31** [comment]
> I have my doubts, that this feature is "widely" implemented. Therefore I recommend to check other implementations before you start to spend your time in.

Widely implemented I don't know but I know that at sierra some of our internal LWM2M code used in production do that. (not based on Leshan)
I don't know if wakaama is able to do that maybe. @weicanqd  maybe you should ask ?

The LWM2M recommend this too [core§6.4.1](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-1-0-641-Observe-Operation): 
```
In order to avoid network traffic increase, the LwM2M Client SHOULD maintain
previous observation states in case of reboot, power cycle.
``` 
So maybe this will make more stack to support it ? :thinking: (Not sure at all)

> Long ago, we tried to discus that OMA - LwM2M - Alternative approach for RFC7641. An alternative, which is not based on stack internal artifacts but on application level data, it would be much easier and also more "portable" among coap-implementations. 

This feature is now part of LWM2M v1.1, called `Send Operation` : see [core§6.4.6](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-6-0-646-Send-Operation) 
#971 is a first tentative to implement it. 

"Send Operation" was created to resolve some drawback of Observation which is often badly used in LWM2M (see [LWM2M-Observe](https://github.com/eclipse/leshan/wiki/LWM2M-Observe))

**Comment by boaks** [comment]
> at sierra some of our internal LWM2M code used in production do that.

Cool. 

> This feature is now part of LWM2M v1.1, called Send Operation : see core§6.4.6

Even cooler :-).

**Comment by sbernard31** [comment]
I think we can close this issue. Do not hesitate to add comment or reopen if needed.
